.gitignore
plotting/__init__.py

Fixed import broken due to file changing location
@martyngigg

Fixed Broken import

---

models/projection/powder/mantid_projection_calculator.py
models/slice/mantid_slice_algorithm.py
models/slice/matplotlib_slice_plotter.py
models/slice/slice_algorithm.py
models/slice/slice_plotter.py
models/workspacemanager/mantid_workspace_provider.py
mslice.py
plotting/pyplot.py
presenters/slice_plotter_presenter.py
tests/slice_plotter_presenter_test.py
views/slice_plotter_view.py
widgets/slice/slice.py
widgets/slice/slice.ui

**To test:**
Load an MD workspace into mslice
specify all 3 binning parameters for for both x and y in slice tab
Then click display slice
Fixes #12 
Fixes #30

Implement MDworkspace slicing

---

plotting/plot_window/plot_figure.py
plotting/plot_window/plot_options.py

This commit got lost as it was accidentally committed to the demo branch rather than #70.
**To test:**
* start MSlice & create a slice
* select the plot options
* type something in the title field
* click cancel and the plot should not be affected

Discard changes if user clicks cancel on dialog box

---

build_all_ui_files.py
misc/MDUtils.py
models/cut/mantid_cut_algorithm.py
models/slice/mantid_slice_algorithm.py
plotting/figuremanager.py
plotting/plot_window/plot_options.py
plotting/pyplot.py
widgets/slice/slice.py

Fixes some errors highlighted by landscape.io
**To test:**
Just check that everything still runs as it should (data loads, can plot slices and make cuts).
No issue number.

Fixed landscape errors and some warnings.

---

mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_options.py
mslice/presenters/plot_options_presenter.py
mslice/tests/plot_options_presenter_test.py
mslice/widgets/cut/cut.py

Refactored PlotOptionsDialog class in preparation for issues #104, #107 and #109
-  Added PlotOptionsPresenter to use model-view-presenter pattern
- Modified PlotOptionsDialog and PlotFigureManager to use new presenter
- Divided PlotOptionsDialog into subclasses depending on plot type (slice or cut)
- Added unit tests for PlotOptionsPresenter
**To test:**
Code review, run unit tests. No changes in UI yet.

Plot Options Refactor 

---

mslice/plotting/plot_window/plot_figure.py

Fixed bug by moving call to mappable.set_clim() to after the log conversion.
**To test:**
See issue #140

Logarithmic color plot bug

---

mslice/app/mainwindow.py
mslice/presenters/cut_presenter.py
mslice/presenters/powder_projection_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/app_test.py
mslice/views/cut_view.py
mslice/views/powder_projection_view.py
mslice/views/slice_plotter_view.py
mslice/views/workspace_view.py
mslice/widgets/cut/cut.py
mslice/widgets/projection/powder/powder.py
mslice/widgets/slice/slice.py
mslice/widgets/workspacemanager/workspacemanager.py

Added a label to the bottom-right corner of the main window that displays 'Busy' if MSlice is working and 'Idle' if it is waiting for input.
**To test:**
- Open MSlice and run any load / calculate projections / slice / cut operation
- Verify 'Busy' appears appropriately.
Fixes #81

Show when MSlice is busy

---

mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/tests/workspace_provider_test.py

Added unit tests for MantidWorkspaceProvider class.
Fixes #156

MantidWorkspaceProvider unit tests

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

**Not to be merged until after #166**
Adds `Symmetrised S(Q,E)` to Intensity menu for slices.
**To test:**
- Display slice
- Click 'Intensity' -> `Symmetrised S(Q,E)`
Fixes #169

Intensity - Add Symmetrised option

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

**Not to be merged until after #166**
Adds an additional option to the Intensity menu for slices.
**To test:**
- Display slice
- Click 'Intensity'
- Click `D2sigma/dOmega.dE`
Fixes #167

Intensity - Add d2sigma/dOmega.dE option

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

Adds `GDOS` to Intensity menu for slices.
**To test:**
- Display slice
- Click 'Intensity' -> `GDOS`
Fixes #171

Intensity - Add GDOS option

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/models/slice/slice_algorithm.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

Plot powder lines over slices.
Populates Information -> Bragg peaks menu on slice window with Aluminium, Copper, Niobium and Tantalum options. A crystal structure can also be loaded from a CIF file.
Fixes #163

Informational overplot - powder lines

---

.idea/workspace.xml
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/quick_options.py
mslice/presenters/quick_options_presenter.py
mslice/tests/quick_options_test.py

Features of a slice plot can now be changed by clicking on them (issue #180). This includes Labels, legends, axis ranges, and overplot lines. This functionality will be extended to cuts in the future.
**To test:**
-  Plot a slice
- Click a feature (axis labels or ranges, legends, overplot lines)
- Change settings in the dialog
- Click OK
- Check that the plot is updated with new settings
- Repeat for each feature
@martyngigg

Plot interactivity - slices

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/plotting/plot_window/plot_figure.py

Prevents blank window + error caused by toggling interactive cut on/off again.
**To test:**
See issue
Fixes #264

Fix error when cancelling interactive cut

---

mslice/models/workspacemanager/file_io.py

Correct changes earlier today that broke saving slices. 
**To test:**
- Save a slice and check there are no errors

Fix save error

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/presenters/slice_plotter_presenter.py
mslice/widgets/slice/slice.py

See commit message.
**To test:**
* Load a file and plot a slice with the energy axis as the Y axis and check the intensity operations.
* Now repeat  the operations with the axes swapped on the slice. 
Fixes #283.

Fix intensity calculations if axis order is swapped

---

mslice/models/workspacemanager/file_io.py
mslice/tests/file_io_test.py

Adds tests for the methods in `file_io.py`. 
**To test:**
Run tests + code review
Fixes #277

Add tests for file saving methods

---

mslice/app/mainwindow.py
mslice/presenters/busy.py
mslice/presenters/cut_presenter.py
mslice/presenters/data_loader_presenter.py
mslice/presenters/powder_projection_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/presenters/workspace_manager_presenter.py

This means that it will always exit correctly regardless of exceptions etc.
**To test:**
Check that busy/idle in the bottom corner still toggles appropriately.
Fixes #272

Use context manager for busy/idle status

---

mslice/cli/_mslice_commmands.py
mslice/widgets/ipythonconsole/ipython_widget.py

Adds load command to CLI.
```
import mslice.cli as mc
mc.load('path_to_file')
```
Fixes #303

Add load command

---

buildscripts/buildscript.sh
buildscripts/create_virtualenv.sh
mslice/tests/slice_algorithm_test.py

Mantid is dropping support for Ubuntu 14.04 and we need a `mantid` package to test `mslice`. Moving the builds to Jenkins to be able to use the same build environment as `mantid`.

Add buildscript for a Jenkins job

---

mslice/models/axis.py
mslice/tests/cut_presenter_test.py
mslice/tests/slice_plotter_presenter_test.py

Add the axis validation that's currently in the cli branch to master to avoid a bug when trying to plot an interactive cut.
**To test**
- Checks interactive cuts can be plotted / update correctly.
Fixes #328

Fix interactive cut bug on master

---

mslice/models/projection/powder/make_projection.py

Prevents a bug caused by MakeProjection storing workspaces in the ADS between executions.
**To Test:**
see issue
Fixes #356

Fix MakeProjection storing in ADS

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/iplot.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/plot_options_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/tests/cut_plot_test.py
mslice/tests/plot_options_presenter_test.py
mslice/tests/quick_options_test.py

Includes common interface for `cut_plot` and `slice_plot` and some minor refactoring.
Fixes #294

Give plot objects consistent interface

---

mslice/models/axis.py
mslice/presenters/cut_widget_presenter.py
mslice/views/interfaces/cut_view.py
mslice/widgets/cut/cut.ui

Modified the error messages displayed in the status bar. They are more understandable.
**To test:**
Start mslice, load data, try to perform a cut without the axis parameters. The error shown should be clearer.
Fixes #371

#371 error messages improved

---

mslice/models/labels.py
mslice/plotting/plot_window/slice_plot.py
mslice/widgets/dataloader/dataloader.py

Removed bug that hides last modified date and time in dataloader
**To test:**
The date and time for each file now shows in the data loader
Fixes #408 .

removed bug that hides last modified date and time #408

---

mslice/models/workspacemanager/file_io.py

Changes `_save_slice_to_ascii` to handle both PSD (`HistogramWorkspace`) and non-PSD (`Workspace`) 2D workspaces to output 4-column text format for both types. Previously `_save_slice_to_ascii` only worked for `HistogramWorkspace` and the Mantid `SaveAscii` algorithm was used for non-PSD workspaces. This is not desired as described in the issue.
**To test:**
Load a non-PSD data file (e.g. `MAR21335_Ei60.00meV.nxs`) and plot a slice. In the plot window click on the save (floppy disk) button and save a text file. Open the text file and check that it is in 4-column format. 
Check that the output text file is ok by e.g. plotting it with gnuplot:
```
gnuplot -e "splot 'tmpws.txt' u 1:2:3 w p; pause -1"
```
Fixes #429.

Save a 4-column text format for non-PSD slices

---

mslice/cli/_mslice_commands.py
mslice/cli/helperfunctions.py
mslice/plotting/plot_window/cut_plot.py
mslice/scripting/__init__.py
mslice/scripting/helperfunctions.py
mslice/tests/cli_helper_functions_test.py
mslice/tests/cli_mslice_projection_test.py
mslice/tests/command_line_test.py
mslice/tests/cut_plot_test.py
mslice/tests/scripting_helperfunctions_test.py
mslice/tests/scripting_tests.py
mslice/tests/slice_plot_test.py

Tests included for script generation and CLI functions
**To test:**
Fixes #435 .

Add tests for script generation and CLI functions

---

mslice/plotting/plot_window/slice_plot.py
mslice/tests/slice_plot_test.py

Updated the update_legend functions as suggested in #446
Fixes #446 .

Update the update_legend function in slice_plot.py

---

README.md

I added instructions in the readme to help linux users set up the python interpreter in Pycharm because it was not clear to me what one to use.
**To test:**

Updated readme to account for Linux developers

---

mslice/presenters/workspace_manager_presenter.py
mslice/scripting/__init__.py

Converted the `if` / `elif` block to a map to function handles in `workspace_manager_presenter`.
Moved the mslice hidden prefix (`__MSL`) parsing part of the script generation to a helper function.
**To test:**
Check that all unit tests pass and everything else works ok.
Fixes #478

Fix flake8 complexity warnings

---

mslice/app/mainwindow.ui
mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/data_loader_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/tests/file_io_test.py
mslice/widgets/dataloader/dataloader.py

Fixes bugs identified in unscripted testing for Mantid 4.2 release
**To test:**
Go through the issues in #511 and check they have been resolved (except the print issue which I could not reproduce, and the colour-scale with information overplot issue which will be handled in a separate PR).
Fixes #511

Unscripted test  bugs

---

mslice/plotting/plot_window/plot_figure_manager.py

Added a check for image formats supported by the Matplotlib `savefig` function, and pops up an error if the user requested a format that Matplotlib does not support.
Also added the ability to save a `jpg` or `jpeg` file. Matplotlib only supports this if the `PIL` or `Pillow` modules are installed. The work-around uses Qt to save the `jpeg`.
**To test:**
Run MSlice, make a plot. 
Click the diskette icon to save a file and select `Image (*.png)`. Type a filename with a valid image extension (e.g. `wmf` - if you specify something else the code will just append `png` to the end and it will save it as a `png`). If this is not supported (e.g. `wmf`) then an popup window will appear saying the format is not supported.
Now try to save again as a `jpg` or `jpeg`. Check that no pop up appears and …

Added check for supported save formats and jpeg output

---

buildscripts/buildscript.sh

Changed buildscript to QT5

---

docs/source/cutting.rst
docs/source/quickstart.rst

Corrected errors in sections 1.4, 2.1 and 2.2
**To test:**
Check sections 1.4, 2.1 and 2.2 of the documentation.
Fixes [#562](https://github.com/mantidproject/mslice/issues/562)

Fixed a few minor errors in the MSlice documentation

---

mslice/widgets/workspacemanager/input_boxes.py

Release-next has the fix for https://github.com/mantidproject/mslice/pull/577
This fix is also required in master.

Merge release-next branch back to master

---

buildscripts/buildscript.sh

Pipes flake8 warnings to a file
**To test:**
CI passes

Pipe flake8 warnings to files

---

buildscripts/buildscript.sh
mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/plotting/plot_window/plot_figure_manager.py
mslice/util/mantid/__init__.py
mslice/widgets/ipythonconsole/ipython_widget.py
setup.cfg
setup.py

Removed references to MantidPlot and Qt4
Fixes #[606](https://github.com/mantidproject/mslice/issues/606).

Removed MantidPlot and Qt4

---

.pre-commit-config.yaml
docs/source/cli.rst
docs/source/cutting.rst
docs/source/quickstart.rst
docs/source/slicing.rst
environment.yml
install-requirements.txt
mslice/presenters/presenter_utility.py

Add a config for pre-commit.
**To test:**
Install pre-commit if necessary.
Run this command on the MSlice repository:
`pre-commit run --all-files`

Pre commit for MSlice

---

mslice/scripting/helperfunctions.py
mslice/tests/cli_helper_functions_test.py
mslice/tests/scripting_helperfunctions_test.py

Added tests for exporting show or hide lines (, errorbars, and legends) to the script

Tests for exporting show or hide lines to script

---

.coveragerc
mslice/tests/cli_helper_functions_test.py
setup.cfg

Updated unit tests and setup configurations. 
In order to get more unit tests for mslice.models there is a separate issue: https://github.com/mantidproject/mslice/issues/598
**To test:**
Ensure all unit tests are running successfully.
Fixes [#496](https://github.com/mantidproject/mslice/issues/496)

Update unit tests

---

mslice/plotting/plot_window/cut_plot.py

Disabled 'Generate Script to Clipboard' to match disabled 'Generate Script File'.

Cleaned up File menu for interactive cuts

---

mslice/plotting/plot_window/cut_plot.py

**To test:**
1. In the Workspace Manager tab select the workspace MAR21335_Ei60meV
2. Navigate to the Cut tab
3. In the row labelled along, set the from value to 0 and the to value to 10
4. In the row labelled over, set the from value to -5 and the to value to 5
5. Click Plot. A new window with a cut plot should open.
6. Navigate to the Information menu on the cut plot
7. Select Aluminium from the submenu for Bragg peaks. Green lines should appear on the cut plot with a respective legend entry.
8. Double click on the green line. A line editor should open. Change the colour of the line and check that plot changed accordingly.
Fixes #655.

Made lines for Bragg peaks editable

---

mslice/models/cut/cut_algorithm.py

Adds a scaling by the number of bins which the workspace was rebinning into in the integration axis in the "Integration" method of `Cut`. For details, see original issue #682
**To test:**
Run the script in the issue #682 and check that the plots with MSlice and with pure Mantid are the same.
Fixes #682

Fix #682 Cut method:Integration scale bug

---

README.md
docs/source/quickstart.rst

Added comment about waterfall plots to 'Plotting a Cut' section of the Quick Start section of the MSlice documentation.
**To test:**
Check grammar and spelling of the changed section.
Fixes #654

Added comment about waterfall plots to docs

---

mslice/app/mainwindow.py
mslice/plotting/observabledictionary.py
mslice/tests/plotselector_model_test.py
mslice/tests/plotselector_presenter_test.py
mslice/tests/plotselector_view_test.py
mslice/util/qt/qapp.py
mslice/widgets/plotselector/model.py
mslice/widgets/plotselector/presenter.py
mslice/widgets/plotselector/test/__init__.py
mslice/widgets/plotselector/view.py

Replaced references to workbench with mslice. Updated comments. Moved tests for plotselector to test folder. Slightly modified plotselector tests to work within MSlice.
**To test:**
Check that the unit tests are running successfully.
Fixes #718

Removed references to workbench and moved tests

---

README.md
mslice/models/workspacemanager/workspace_algorithms.py

Adds some instructions to the README to work with the new Mantid conda packages in PyCharm.
**To test:**
Check that the instructions work for you (I've only tested on Windows).
No associated issue

Update README.md with conda pycharm instructions

---

.github/actions/publish-package/action.yml

Fixed problem with default for shell.
**To test:**
Code review only.

Set shell in each step instead of as default

---

mslice/__init__.py

Update version number from 2.3.1 to 2.4

Update version number to 2.4.

---

README.md
docs/source/quickstart.rst

Both the README.md and section 1.1. Starting MSlice of the online documentation were updated with information on MSlice conda builds.
**To test:**
Read the new instructions and check that they make sense and that spelling and grammar are ok.
Fixes #801

Added information about MSlice conda packages

---

mslice/__init__.py

For the upcoming release of MSlice the version number has changed from 2.4 to 2.5.
**To test:**
Code review only ;-)

Update version number for upcoming release

---

.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nightly.yml
README.md
environment.yml
pyproject.toml

This PR updates the badges in the README file.
**To test:**
Code review
See that the test coverage is reported on the Coveralls webpage under the "Builds" section:
https://coveralls.io/github/mantidproject/mslice
This build was a test build that I triggered by modifying the `uni_tests.yaml`. In the future, it will only be triggered by the `unit_tests_nightly.yaml`
Fixes #889

Update badges in README

---

.github/actions/publish-package/action.yml
.github/workflows/deploy_conda_nightly.yml

In the last 10 months, MSlice was using `conda build` after problems with `mamba build`. Now it has been replaced with` conda mambabuild` to use the faster mamba solver.
**To test:**
Code review only.
Fixes #953.

Replaced conda build with conda mambabuild

---

.github/workflows/online_doc_update.yml
.pre-commit-config.yaml

Sphinx went from version 1 to 3.

Update sphinx version

---

.github/workflows/online_doc_update.yml

correct sphinx version

---

.github/workflows/online_doc_update.yml
docs/source/conf.py

Updated copyright year in documentation. This can only be verified in the code or, after merging into main, on the website with the documentation: https://mantidproject.github.io/mslice/

Update copyright year

---

docs/source/cli.rst

Added an example script for saving multiple cuts as ASCII files. 
Also, corrected an import error in the section "Plotting a series of cuts".
**To test:**
Read instructions and see whether they make sense. Try out the example script.
Fixes #1023.

Added section on how to save multiple files via CLI

---

pyproject.toml
src/mslice/plotting/plot_window/cut_plot.py
src/mslice/plotting/pyplot.py

Upgrade from matplotlib 3.8.4 to 3.9.2
A new version of pyplot was generated.
**To test:**
Just try to use MSlice, especially different types of plotting, also waterfall plots with offsets.
Fixes #1035.

Upgrade matplotlib to version 3.9.2

---

src/mslice/models/cut/cut.py

Cleaned up code that became redundant after a recent bug fix.
**To test:**
Code review only (see https://github.com/mantidproject/mslice/pull/1067)
Fixes #1068.

Removed unused code
