mantidproject/mslice

.gitignore
models/projection/powder/mantid_projection_calculator.py
models/projection/powder/projection_calculator.py
mslice.py
presenters/powder_projection_presenter.py
tests/powder_projection_presenter_test.py
widgets/projection/powder/powder.py
widgets/slice/slice.py
widgets/workspacemanager/workspacemanager.py

Will transform the current selected workspace to MD workspace if user clicks on calculate powder projection
**To Test:**
Load a workspace 2d into mslice, select the checkbox next to it in the workspace manager
And click on the calculate projections button on the powder tab
A new workspace should appear in the in the workspacemanager tab with the suffix 'MD'
resolves #11

Implement calculate projections

---

.coveragerc
.travis.yml
mainview.py
mslice.py
presenters/interfaces/main_presenter.py
presenters/interfaces/powder_projection_presenter.py
presenters/interfaces/slice_plotter_presenter.py
presenters/interfaces/workspace_manager_presenter.py
presenters/main_presenter.py
presenters/powder_projection_presenter.py
presenters/slice_plotter_presenter.py
presenters/validation_decorators.py
presenters/workspace_manager_presenter.py
tests/main_presenter_test.py
tests/powder_projection_presenter_test.py
tests/slice_plotter_presenter_test.py
tests/workspacemanager_presenter_test.py
views/powder_projection_view.py
views/slice_plotter_view.py
views/workspace_view.py
widgets/projection/powder/powder.py
widgets/slice/slice.py
widgets/workspacemanager/command.py
widgets/workspacemanager/workspacemanager.py

Implements a system that when the currently selected workspace is changed will notify all subscribed 'listeners'
This allows things like the tabs to update the contents of its combo boxes according to the currently selected worskpace
**To test:**
Load (preferably multiple workspaces) to the work space manager. Any changes to the currently selected worskpaces will be printed to the console. This print call is from a subscribed listener (the slice presenter)
Fixes #19 .
Fixes #33

Implement workspace selection changed notification system.

---

mslice.py
widgets/workspacemanager/workspacemanager.py

Refactored workspacemanager widget to emit errors as signals rather than to handle them on the widgets
**To test:**
Open MSlice and make the workspacemanager show an error on the statusbar.
For example click Remove/Save/Rename without having a workspace selected
Fixes #24

Refactored workspace provider widget to emit errors as QSignals

---

models/workspacemanager/mantid_workspace_provider.py
presenters/workspace_manager_presenter.py
tests/workspacemanager_presenter_test.py
views/workspace_view.py
widgets/workspacemanager/workspacemanager.py

Fixes bug where mslice would fail to save any MDworkspace
**To test:**
A)
1.  Load an MD workspace into MSlice.
2. Select the select the MDWorkspace loaded/created in mslice and you should be able to save it with the save button. Verify new file is created
3. Verify that the QDialog that shows  up while saving forces the .nxs extension
B)
Try to load an invalid file  non workspace file, An error message should pop uo
C)
Try to load a file and close the dialogbox without selecting anything. Nothing should happen
D)
Try to save a file and close the dialogbox without selecting anything. An appropriate message should be shown
E)
Try to save to file you do not have permission to write (or in any other way cause the mantid SaveNexus/SaveMD to fail). An appropriate blanket  'save has failed' …

Fix MD workspace saving and Add error Handling to Save/Load

---

models/projection/powder/mantid_projection_calculator.py

Changed projection calculation to pass `dEAnalysisMode` from input file to `ConvertToMD`. This allows support for indirect geometry data files.
**To test:**
Try to load the following file:
[iris26176_graphite002_red_nxs.zip](https://github.com/mantidproject/mslice/files/456472/iris26176_graphite002_red_nxs.zip)
It should fail without this patch and succeed with it.
Fixes #65 .

Modified projection calculation to support Indirect mode

---

widgets/workspacemanager/workspacemanager.py
widgets/workspacemanager/workspacemanager.ui

Changed the workspace manager view to make selection done by clicking instead of by checkboxes. To select multiple workspaces 
**To test:**
Open MSlice and load multiple workspaces. Attempt to 
1. Delete a single workspace
2. Remove multiple workspaces
3. Make sure that when a projection is selected that the slice tab gets autopopulated as expected.
Fixes #40

Removed checkboxes from workspace manager

---

models/projection/powder/mantid_projection_calculator.py
presenters/powder_projection_presenter.py
tests/powder_projection_presenter_test.py
views/powder_projection_view.py
widgets/projection/powder/command.py
widgets/projection/powder/powder.py

**To test:**
Load a file.  Try calculating the projections.
A new workspace with `_QE` suffix will appear
Switch The projection axis in the projection tab and calculate the projection again.
A new workspace with `_EQ` suffix will appear.
Plot Slices for booth and verify they are both correct
Fixes #64

Allow axis switching in projections

---

mslice.py
presenters/cut_presenter.py
presenters/powder_projection_presenter.py
presenters/slice_plotter_presenter.py
presenters/workspace_manager_presenter.py
tests/cut_presenter_test.py
tests/powder_projection_presenter_test.py
tests/slice_plotter_presenter_test.py
tests/workspacemanager_presenter_test.py
views/cut_view.py
views/powder_projection_view.py
views/slice_plotter_view.py
views/workspace_view.py
widgets/cut/cut.py
widgets/projection/powder/powder.py
widgets/slice/slice.py
widgets/workspacemanager/workspacemanager.py

Errors will stay in the statusbar until a button is clicked
**To test:**
1. Launch the mslice GUI.
2. Click on remove workspace without any workspace selected. An error will appear
3. Clicking on any other button will cause the error to disappear. 
Fixes #75

Do not clear error messages after a timeout

---

models/projection/powder/mantid_projection_calculator.py
models/projection/powder/projection_calculator.py
presenters/powder_projection_presenter.py
tests/powder_projection_presenter_test.py
widgets/projection/powder/powder.ui

In the projections tab the term energy was used an input even though output workspace was in DeltaE vs |Q|. Although the resulting plots did have correct legends this may become a source of confusion in MSlice if more units are added.
**To test:**
1. Open Mslice. 
2. Verify that the projections tab dropdown menu has a `|Q|` entry and a `DeltaE` entry and that is does not have an `Energy` entry.
Fixes #82

Remove misleading references of energy from mslice.

---

.travis.yml

Install mantid package on the build server. It requires Trusty so that requirement has been added
**To test:**
Builds should pass.
Fixes #34

Install nightly mantid build on travis

---

cli/_mslice_commmands.py
models/projection/powder/mantid_projection_calculator.py
models/projection/powder/projection_calculator.py
presenters/powder_projection_presenter.py
tests/powder_projection_presenter_test.py

Added wavenumbers `cm-1` as a possible energy unit. 
**To test:**
Load a dataset and select `cm-1` from the `units` combo box, and calculate projection. Check that the resulting MD workspace has energy which is scaled by 8.066 compared to the MD workspace created with `units=meV`. The new workspaces should have a `_cm` suffix.
Fixes #63.

Implement wavenumber conversion

---

models/projection/powder/mantid_projection_calculator.py
presenters/powder_projection_presenter.py
tests/powder_projection_presenter_test.py
views/powder_projection_view.py
widgets/projection/powder/powder.py

This PR adds a `2Theta` axis to the list of possible *x*-, or *y*-axes (`u1` or `u2`). The implementation uses `ConvertSpectrumAxis` on the input workspace and the `ConvertToMD` with the `CopyToMD` method. (Note: For indirect geometry instrument data, `PreprocessDetectorsWS` which is run by `ConvertToMD` doesn't work on the output of `ConvertSpectrumAxis` for some reason - probably a bug. However, if it's run first on the original input workspace, then the detector workspace is used in `ConvertToMD`, a valid `MDWorkspace` is created. This work-around is used in this PR).
**To test:**
In the mslice GUI, load a file, and select `2Theta` as `u1` and `DeltaE` as `u2` (or vice versa). Calculate projection and plot the slice - check that the `2Theta` axis is in `Degrees` and the data looks …

Theta axis implementation

---

.travis.yml
presenters/interfaces/main_presenter.py
presenters/interfaces/workspace_manager_presenter.py
presenters/main_presenter.py
presenters/workspace_manager_presenter.py
tests/workspacemanager_presenter_test.py
views/workspace_view.py
widgets/workspacemanager/workspacemanager.py

This allows multiple files to be selected in the `Load` dialog box (using `getOpenFileNames` - allowin shift-select and also left-click-and-drag), and for all selected files to be loaded into the workspace manager.
**To test:**
Click `Load` and select multiple files. Check that all the files which can be loaded are loaded into the workspace manager. Files which cannot be loaded should be listed in the error bar at the bottom. Files which have the same names as existing workspaces should bring up a prompt asking if user wants to overwrite (one for each name conflict).
Fixes #100

Enable loading of multiple files

---

mslice/app/__init__.py

Fixes lifetime issue with the reference to the `MainWindow` being cleaned up before the program had exited. 
**To test:**
This only appeared to be an issue on RHEL7 with Gnome but it should have been general.
* start mslice with `./mslicedevel`
* load and calculate a projection
* plot a slice and keep the window
* change some slice parameters and plot another slice
* a new window should appear and the main GUI should stay visible.
Before this fix the main mslice window disappeared on RHEL7. 
Fixes #112

Keep reference to MainWindow alive

---

misc/MDUtils.py
mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py
mslice/widgets/cut/cut.py

Enables the saving of cuts to text files in a three-column `x`, `y`, `e` format. 
If multiple cuts area selected, each will be saved to a separate file with the same starting prefix.
**To test:**
Open a data file, make a cut and click `Save ASCII` in the `Cut` tab. Select a file name and check that the correct data (and header, indicating the limits of the cut and original workspace name) is written to that file. Select multiple cuts and check that the correct number of files are written with the correct data. 
Fixes #108.

Save ASCII

---

mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py
mslice/views/cut_view.py
mslice/widgets/cut/command.py
mslice/widgets/cut/cut.py

Stores previously entered parameters for cuts (along which axis, from, to, step, integration range, smoothing level, whether to normalise to unity) in an attribute of `CutPresenter`. When the user changes back to a previously defined cut/workspace pair (or a new workspace with the same axes), will repopulate the fields in the `Cut` tab with the previously defined values.
**To test:**
Load several data files and calculate several sets of projections (convert to MDWorkspace) for each dataset, ensuring that you have at least two of the same type (e.g. two `_QE` and one `_EQ` or whatever). Make some cuts, and check that when you select another workspace or axis, and then select the previous one again, that the correct values for the previous cut reappear.
Fixes #106

Remember cut parameters

---

mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/workspacemanager_presenter_test.py
mslice/views/workspace_view.py
mslice/widgets/workspacemanager/inputdialog.py
mslice/widgets/workspacemanager/workspacemanager.py

Checks if loaded file is for an indirect geometry instrument and if so if `Efixed` is set. NXSPE files do not store `Efixed` which is need for conversion to `Q`. If `Efixed` is not set, creates a dialog to ask the user for `Efixed` and update the workspace with information.
**To test:**
Load an indirect geometry nxspe file (e.g. here: 
[iris_nxspe.zip](https://github.com/mantidproject/mslice/files/844198/iris_nxspe.zip) and check that a dialog appears asking for `Efixed` - for Iris data, put in Efixed=1.84 meV. Then check that calculate projections work for this dataset (previously it did not work). Check that loading of all other files (direct geometry nxspe, all nxs) files still work without the dialog appearing.
Fixes #117.

Indirect geometry NXSPE handling

---

mslice/app/mainwindow.py
mslice/models/cut/cut_algorithm.py
mslice/models/cut/cut_plotter.py
mslice/models/cut/mantid_cut_algorithm.py
mslice/models/projection/powder/mantid_projection_calculator.py
mslice/models/projection/powder/projection_calculator.py
mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/models/slice/slice_algorithm.py
mslice/models/slice/slice_plotter.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/presenters/cut_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/presenters/interfaces/powder_projection_presenter.py
mslice/presenters/interfaces/slice_plotter_presenter.py
mslice/presenters/interfaces/workspace_manager_presenter.py
mslice/presenters/powder_projection_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/app_test.py
mslice/tests/cut_presenter_test.py
mslice/tests/slice_plotter_presenter_test.py
mslice/views/cut_view.py
mslice/views/powder_projection_view.py
mslice/views/slice_plotter_view.py
mslice/views/workspace_view.py
mslice/widgets/cut/cut.py
mslice/widgets/projection/powder/powder.py
mslice/widgets/slice/slice.py
mslice/widgets/workspacemanager/workspacemanager.py

Implements using `SofQWNormalisedPolygons` (`SofQW3`) to rebin data (usually from MARI or with a "rings" mapping) where pixel sizes are large before conversion to MDWorkspace with the `CopyToMD` method. For large datasets (and for indirect geometry data), the direct conversion to `|Q|` using `ConvertToMD` is still used because the centre-point rebinning of `BinMD` is not a problem in those cases.
Also, implemented a calculation of the `|Q|` limits and steps from the detector angles in the datafile at loading, which is attached to the `WorkspaceProvider` as a property. This required changing the `MainWindow` code to ensure that all widgets and presenters run the same instance of `WorkspaceProvider`. 
**To test:**
Load data (single or multiple files). If the data is direct inelastic from …

Bin step size limits and using SofQW3 to Q conversion

---

mslice/models/slice/matplotlib_slice_plotter.py
mslice/presenters/cut_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/views/slice_plotter_view.py
mslice/widgets/slice/slice.py

This PR addresses several issues:
- #124 - Selecting a previously saved cut does not clear the `width` parameter but disables the edit box, so if this value was previously non-`None`, it can give a repeated set of the same cuts. Also fixed a bug in the code to remember previously set parameters - non-cutable saved cuts will overwrite the parameters of the previous cutable workspace.
- #123 - Make the workspace name the slice title
- #72 - The slice widgets are now disabled when a non-sliceable workspace is selected. (sorry wrong issue in the commit)
**To test:**
Load a dataset and calculate projection - check that selecting the projected workspace enables the slice widgets, and selecting the original dataset disables it. Check with other non-sliceable workspaces (e.g. saved cuts) and …

General bug fixes

---

mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/plot_options.ui

Implements the option to change the scale to log for the `x` and `y` axes of a cut.
**To test:**
Loads a dataset, calculate projection and make a cut. Go to plot options and select `Logarithmic`, and click ok. Check the result is in log-scale. The `symlog` option (symmetric-logarithmic) of Matplotlib is used so negative data can be handled with the region below the minimum data point strictly not zero in a linear scale. If the data has no negative values check that the scale is truncated below the minimum data value.
Fixes #125

Logarithmic scale on cuts

---

.idea/misc.xml
.idea/modules.xml
.idea/mslice.iml
.idea/preferred-vcs.xml
.idea/vcs.xml
.idea/workspace.xml
.travis.yml
README.md
mslice/app/__init__.py
mslice/tests/app_test.py
mslice/tests/cut_presenter_test.py
mslicedevel.bat
mslicedevel.sh
setup.py

Adds a basic PyCharm project that has useful runnable configurations in it. It required implementing an `--inplace` option on the `build_py` command so that the `ui_` files were generated next to the original source. This makes debugging the original source actually possible.
It currently does not support IPython integration. This needs to be fixed.

Add PyCharm support to mslice

---

mslice/app/__init__.py
mslice/external/ipython.py

IPython 2 contained a bug when using PyQt4v1. A previous import of PyQt4
would always cause an error when loading IPython due to a logic error
in its interal import mechanism.
We now patch the faulty function with a fixed definition for those
versions affected.
This was mainly an issue on Ubuntu 16.04 that now comes with IPython 2.

Add shim around IPython import to patch around a bug

---

mslice/presenters/workspace_manager_presenter.py
mslice/tests/workspacemanager_presenter_test.py
mslice/widgets/workspacemanager/workspacemanager.py

Can now save multiple selected workspaces at once.
**To test:**
- Load/generate workspaces in the workspace manager
- Select multiple workspaces with ctrl or shift
- Click Save
This produces a dialog that asks which directory to save the files.
Fixes #141

Save multiple selected workspaces

---

mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/plot_options.ui
mslice/presenters/plot_options_presenter.py
mslice/tests/plot_options_presenter_test.py

Added various options to change the appearance of lines in cut plots.
- Refactored legends code to be more extendable and removed redundant data
- Added controls to UI for line appearance ( line colour, style, width, marker type and show/hide)
- Add unit test to presenter for new line controls
**To test:**
- Open any cut plot
- Click plot options
- Change values for line colour / style / width / marker and click OK
Fixes #104 
Fixes #109

Line Display Options

---

mslice/models/slice/matplotlib_slice_plotter.py

Removes call to `show` when plotting a slice.
**To test:**
See issue for testing instructions.
Fixes #160.

Remove unneeded `show` call.

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

Plot recoil lines over slices (from issue #163).
Added options to the Information -> Recoil lines menu on slices to toggle Hydrogen, Deuterium or Helium recoil lines. There is also an option to plot any other atom by entering the relative mass.

Informational overplot - recoil lines

---

mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py

Fixes a bug where if the `width` parameter was set, and multiple workspaces were selected, only the first workspace would be plotted. This was due to a bug in the parameter caching mechanism which meant that parameters for non-first workspaces were not set.
**To test:**
Load and calculation projection for multiple (>1) workspaces. Select multiple projected workspaces. In the cut tab, set finite values for all parameters, including `width`, and `Plot`. Check that all selected workspaces were plotted.
Fixes #162

Multiple cuts (finite `widths`) of multiple workspaces

---

mslice/models/cut/cut_algorithm.py
mslice/models/cut/mantid_cut_algorithm.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/models/workspacemanager/workspace_provider.py
mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py
mslice/views/cut_view.py
mslice/widgets/cut/cut.py

The code to store cut parameters previously defined by the user in the `Cut` tab has now been moved into the `MantidWorkspaceProvider` class from the `CutPresenter` class. This means that workspace operations (especially `RenameWorkspace`) will not break the caching system (because the parameters are stored as `dict` entries keyed by the workspace name).
**To test:**
Load several input files and calculate projections for them (making sure they are the same type, e.g. all Q-E or 2theta-E). Select one of the projected workspace and go to the cut axis and put some numbers into the fields there. Now click on another projected workspace and check the numbers in the fields remain unchanged. Click on a non-projected workspace and check the numbers are cleared and fields are disabled. Click again …

Refactored cut parameter cache code

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/plot_options_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/tests/cut_plot_test.py
mslice/tests/plot_options_presenter_test.py
mslice/tests/quick_options_test.py
mslice/tests/slice_plot_test.py

This changes PlotFigureManager class to only include code that is common to both slices and cuts, and puts the specific methods into new classes, `SlicePlot` and `CutPlot`. This simplifies the classes and makes it much easier to test important methods.
**To test**
run `SlicePlotTest` and `CutPlotTest`
Fixes #186

Refactor PlotFigureManager using separate slice/cut classes

---

mslice/plotting/plot_window/slice_plot.py

After refactoring of the cut/slice figure managers, overplotting of recoil lines with arbitrary mass and CIF file powder lines no longer work. This PR fixes these bugs.
**To test:**
Run MSlice and check that recoil lines with arbitrary mass now plots, and can also be removed by unchecking the corresponding menu option. Check that the powder lines for an arbitrary CIF file can also be plotted and removed.
Fixes #189.

Fixed CIF and arbitrary recoil overplot bugs

---

mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py
mslice/tests/workspace_provider_test.py
mslice/views/cut_view.py
mslice/widgets/cut/cut.py
mslice/widgets/slice/slice.py

Users reported that the default Q-step sizes is sometimes too small, leading to `NaN` in the plots (white pixels or gaps in line plots). This is because the current algorithm uses the smallest difference between detector angles which may only apply to a small part of the detector area. 
This PR changes the minimum value to be around 0.6 degrees, in order to avoid the `NaN` problem. 
Also, it changes the behaviour of when the default step sizes are used - previously the user had to put a zero `0` in the edit box to trigger the default value to be used. Now, if the value is empty or is otherwise invalid, the default value is used.
**To test:**
Load a MERLIN reduced dataset (e.g.: `MER30936_Ei10.00meV_Rings.nxspe` 
[MER30936_Ei10.00meV_Rings.zip](https://github.com/mantidproject/mslice/files/ …

Minimum step in automatic bin size estimate

---

mslice/app/__init__.py
mslice/app/mainwindow.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/quick_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/plotting/pyplot.py
mslice/presenters/cut_presenter.py
mslice/quickview/QuickView.py
mslice/quickview/ui_mock.py
mslice/tests/app_test.py
mslice/tests/cut_presenter_test.py
mslice/util/qt/QtCore.py
mslice/util/qt/QtWidgets.py
mslice/util/qt/__init__.py
mslice/util/qt/functions.py
mslice/util/qt/uic.py
mslice/widgets/cut/cut.py
mslice/widgets/projection/powder/powder.py
mslice/widgets/slice/slice.py
mslice/widgets/status/status.py
mslice/widgets/workspacemanager/inputdialog.py
mslice/widgets/workspacemanager/workspacemanager.py

Adds a basic shim in `mslice.util.qt` to wrap `qtpy` which again wraps an actual Qt/Python binding. This is because `qtpy` is not installed on Windows versions of Mantid; and also is not compatible with running MSlice within a MantidPlot instance (because it initializes `PyQt4` with `sip` API version set to `1` for some functions whilst `qtpy` requires API version 2 for everything.
**To test:**
Download zip / `git clone` on Windows and check `mslicedevel.bat` runs ok. 
Run the attached script ([mslice_in_mantidplot.zip](https://github.com/mantidproject/mslice/files/1632400/mslice_in_mantidplot.zip)) within MantidPlot; download this branch `192_pyqt_bindings` and check that it runs ok.
Fixes #198

Another pyqt shim

---

mslice/plotting/pyplot.py

Adds `figure.show()` to end of each plot action. This ensures that even if the user has closed the figure (clicked `x` on the menu bar), that it will be re-opened again when they click plot. For some reason this was not necessary when the `ui`s were compiled but appears to be needed now that they are loaded using `uic.loadUi`
**To test:**
Make a slice or cut and plot it. Close the window. Click plot again and check the window reappears and data is correctly plotted.
Fixes #199

Re #199 - ensure plot window shows when plot clicked

---

mslice/plotting/plot_window/slice_plot.py

Changing the intensity type of a slice - e.g. from S(q,w) to chi''(q,w) - effectively requires the colour (intensity) data to be replotted which means that any overplotted lines (recoil or powder lines) will also be erased. This PR searches through the allowed line types and replots them if needed - effectively preserving the state of the slice plot window.
**To test:**
Plot a slice. Overplot a recoil line or powder line (or many instances or mix of each). Change the intensity type (e.g. from S(q,w) to d2Sigma/dOmega.dE) and check that the overplotted lines remain.
Also check that the grid [if enabled] and (color) axis type (e.g. linear or log) is also preserved.
Fixes #184

Preserve overplot lines on changing intensity type in slices

---

mslice/plotting/plot_window/plot_figure.py

Allows the plot options to be accessed by right-clicking as well as double-clicking.
**To test:**
- Check the options for axis, titles, and lines on a plot figure open on right-click.
Fixes #211

Add right-click condition to plot options

---

mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/slice_plot.py

Recent changes broke the option to change the style of recoil / powder lines by double-clicking. This fixes the issue.
**To test:**
- Plot a slice
- Plot a line using the information menu
- Double click the line (or legend) and change the properties
- Press ok
- Verify that the line changed correctly
Fixes #210

Fix quick_options error when editing recoil/powder lines

---

mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py

A sample temperature can now be entered by value rather than using a sample log entry. 
**To test:**
- Plot a slice
- Change Intensity option
- Enter a number instead of choosing from the list
Fixes #212

Add sample temperature by text box

---

mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/presenters/main_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/widgets/workspacemanager/workspacemanager.py
mslice/widgets/workspacemanager/workspacemanager.ui

**Not to be merged until after #208**
Implements new `WorkspaceManager` design with tabs for each workspace type. The save / rename / combine controls remain but have moved. The `Load` command is now handled by the `DataLoaderWidget`, not the `WorkspaceManager`. 
**To test:**
- Using the `Data Loading` tab, load workspaces of each type (`Workspace2D`, `MDEventWorkspace`, `MDHistoWorkspace`) and check they are placed in the correct `WorkspaceManager` tab.
- Also check that the save / rename / combine controls function as previously.
Fixes #207

Split WorkspaceManager into tabs

---

mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/models/cut/cut_algorithm.py
mslice/models/cut/cut_plotter.py
mslice/models/cut/mantid_cut_algorithm.py
mslice/models/cut/matplotlib_cut_plotter.py
mslice/presenters/cut_presenter.py
mslice/presenters/data_loader_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/presenters/main_presenter.py
mslice/presenters/powder_projection_presenter.py
mslice/tests/cut_presenter_test.py
mslice/widgets/cut/command.py
mslice/widgets/cut/cut.py
mslice/widgets/cut/cut.ui
mslice/widgets/workspacemanager/workspacemanager.py

**Not to be merged until after #209**
- Add some workspace type specific controls to `main_window`
- Each cut is now saved as a workspace
- Some refactoring to `mslice.models.cut` to allow `MDHistoWorkspaces` to be loaded / plotted independently. Before, the cut parameters and parent workspace were cached and re-run every time the cut was plotted. Now, the data is saved and read from the `MDHistoWorkspace`.
- Changed name of cuts that are saved to a file to include integration limits -  before, they looked like `MAR21335_Ei60.00meV_QE_cut1` with an incrementing index on the end. Now they look like this: `MAR21335_Ei60_meV_QE_cut(-1.0,1.0) `
- Automatically change tabs after load/powder/plot cut operations
**To test:**
- Test all buttons that appear on each workspace tab function as …

Changes to cuts for new interface

---

mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/slice_plot_test.py

Before, closing or re-plotting the figure in any way would remove the overplot lines, but they would still appear as ticked in the menu. Now the lines are shown again when the figure is opened.
**To test:**
- Plot a slice and some overplot lines
- Close and reopen it / change the colourmap / plot a different slice / etc.
- Check lines are still there.
Fixes #215

Maintain overplot lines between figures

---

mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui

Replaces the text in the toolbar of the plot window with icons for the most obvious controls.
Fixes #232

Add icons to plot window

---

mslice/app/mainwindow.py
mslice/app/mainwindow.ui

Starting the new gui layout in MantidPlot leads to a malfunctioning IPython terminal. As it is not really useful until the CLI is ready it was decided that we should disable it.
**To test:**
Start the GUI and observe that the IPython terminal is not loaded.

Disable IPython console.

---

mslice/models/cut/cut_algorithm.py
mslice/models/cut/mantid_cut_algorithm.py
mslice/models/slice/mantid_slice_algorithm.py
mslice/presenters/cut_presenter.py

`mslice` by default plots all data using the `NumEventsNormalization` whatever the underlying data type. This is fine for histogrammed data which is converted to MD but is incorrect for event data because the normalisation has already been applied during reduction. For these data, `NoNormalization` should be used. This is why SNS event data (autoreduced nexus files, rather than autoreduced `nxspe` files which are histogrammed) is displayed incorrectly.
Edit: also removed ascii saving code in `cut_presenter.py` which is no longer used (there will be a separate PR to add saving to ascii as an option for the `Save` button in addition to the default `nxs`), and moved a function which calls a mantid algorithm from `cut_presenter.py` to `mantid_cut_algorithm.py`.
**To test:**
Load an SNS event …

Handle `displayNormalization` for event data

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py

Puts in the correct equation for the recoil lines for `2theta`-`DeltaE` slices. The derivation involves equating the expression for the energy transfer `E` vs the momentum transfer `Q` (`E = hbar^2 Q^2 / 2 m`) and the expression for the momentum transfer in terms of the scattering angle (obtained by squaring the vector expression for **Q** = **k_i** - **k_f** (`Q^2 = k_i^2 + k_f^2 - 2|k_i||k_f|cos(2theta)`). 
The derivation is here and relies on the Taylor expansion of the square root term (to second order):
**To test:**
Run `mslice` and make a `2theta`-`energy` projection. Plot the projected workspace as a slice. Then overplot the recoil lines. Check that it goes up to ~50-60 degrees rather than cuts off below 10 degrees as previously.
Fixes #214.

Recoil lines for 2theta slices.

---

mslice/models/slice/mantid_slice_algorithm.py

Ticking the 'norm to 1' option in the slice widget would plot a blank slice. This is because the min/max methods used returned NaN values. They've been changed to methods which ignore the NaNs correctly.
**To test:**
- Plot a slice with 'norm to 1' ticked.
Fixes #213

Fix norm to 1 blank slice bug

---

mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/slice_plot_test.py

There was a problem where multiple recoil lines would sometimes be plotted after multiple slices have been displayed. This is because a single `PlotFigureManager` is used for all slices, but it creates a new `SlicePlot` object every time.
This PR addresses this issue whilst retaining the behaviour of the recoil lines to display being kept between plots.
**To test:**
- Display a slice
- Display a different slice and overplot recoil lines
- Check that the recoil lines currently displayed remains constant between both slices, and there are no duplicate lines/legend entries.
Fixes #243

Fix duplicate recoil lines being displayed

---

mslice/plotting/plot_window/plot_window.ui
mslice/plotting/plot_window/slice_plot.py

The zoom in control now appears checkable to match its behaviour, and turns off automatically when 'Interactive cuts' is clicked. 
Fixes #248

Make Zoom in control toggle correctly

---

mslice/models/slice/matplotlib_slice_plotter.py

Showing / hiding an overplot line on a slice using the `Information` menu now also correctly shows/hides the line markers.
**To Test:**
- Plot a recoil line over a slice
- Double-click the line and change the marker
- Check hiding and showing line again also shows/hides the markers.
Fixes #244

Show and hide markers with overplot lines

---

mslice/models/workspacemanager/mantid_workspace_provider.py

Adds a check for `nan` when loading an indirect `nxspe` file.
**To test:**
Load the attached file: [iris67606_graphite002_red.zip](https://github.com/mantidproject/mslice/files/1793298/iris67606_graphite002_red.zip)
Calculate projection and then check that the default values for Q are not nan.
Fixes #258.

Check for `nan` in `EFixed` when loading indirect `nxspe`

---

mslice/presenters/slice_plotter_presenter.py
mslice/widgets/slice/slice.py

Makes sure the min / max / step values of the axes in a slice are updated when the user changes which axis should be x and y.
**To test:**
Load a workspace and create a projection. In the slices tab, change the axes and check that the values are updated correctly. 
Fixes #242

Swapping of min/max/step values when slice axes change

---

mslice/presenters/cut_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/presenters/main_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/widgets/workspacemanager/workspacemanager.py

Appends an asterisk to the `MD Histo` tab to show new workspaces instead of changing to it automatically.
(This was by far the easiest way to implement tab highlighting, changing font color/style is possible but requires more code.)
**To test:**
- Create a cut
- Instead of switching to `MD Histo` tab, it should appear as `MD Histo*`
- Upon clicking the `MD Histo` tab, asterisk disappears.
Fixes #256

Highlight when tab has new workspaces

---

mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/interactive_cut.py

Fixes some MDHisto related bugs.
**To test:**
1. 
- Load a cut.
- Check there are no errors and that it loaded correctly.
2.
- Plot a slice and create an interactive cut.
- Click 'save cut'.
- Go to `MDHisto` tab.
- Should be able to select and plot the cut without errors.
Fixes #265

Fix MDHistoWorkspace errors

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/models/slice/slice_algorithm.py
mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/models/workspacemanager/workspace_provider.py
mslice/plotting/plot_window/plot_figure.py
mslice/presenters/data_loader_presenter.py
mslice/presenters/main_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/workspacemanager_presenter_test.py

**Shouldn't merge until after #253**
Output a slice to ASCII or matlab. Works by caching the `MDHistoWorkspace` outputted by `BinMD` in `SliceAlgorithm`'s `compute_slice` as a hidden workspace. If no hidden workspace is found, runs `compute_slice` with default parameters.
Fixes #255

Save slices as ASCII or matlab

---

mslice/presenters/data_loader_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/tests/data_loader_test.py

Reinstates old tests surrounding loading data for new `data_loader` class and adds some new ones.
Fixes #238

Create unit tests for data loader

---

mslice/models/cut/cut_plotter.py
mslice/models/cut/matplotlib_cut_plotter.py
mslice/presenters/cut_presenter.py

There was a bug which prevented the intensity range from being set when plotting a cut. This is to do with the order of calls in the `cut_plotter`. `ylim` must be set before drawing but after the line is plotted.
**To test:**
- Plot a cut inputting some range for the intensity values
- Ensure y axis on plot matches input intensity values
- Close plot and click plot again
- Check the intensity values are still correct (sometimes only saw the bug on second attempt.)
Fixes #271

Fix ylim not setting correctly

---

mslice/app/mainwindow.py
mslice/models/alg_workspace_ops.py
mslice/models/cut/cut_plotter.py
mslice/models/cut/mantid_cut_algorithm.py
mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/projection/powder/mantid_projection_calculator.py
mslice/models/slice/mantid_slice_algorithm.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/models/slice/slice_plotter.py
mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/cut_presenter_test.py
mslice/tests/workspacemanager_presenter_test.py
mslice/views/cut_view.py
mslice/widgets/cut/command.py
mslice/widgets/cut/cut.py
mslice/widgets/cut/cut.ui
mslice/widgets/slice/slice.py
mslice/widgets/slice/slice.ui
mslice/widgets/workspacemanager/workspacemanager.py
setup.cfg

This PR adds a different workflow for non-PSD type data (from MARI or from other instruments using a `rings_map`). These data are defined by having detector lists in order sorted by `2theta` angles. The main characteristics is that there are few detectors in these data, and that centre-point rebinning (using  `ConvertToMD`) is not suitable. Until now, the work-around has been to use `SofQW3` to rebin the data into fine `|Q|` bins and then to convert to MD. However, this two step binning process overestimates the uncertainty (errors), because the first step involves partitioning bins. It would thus be better if the workflow includes only a single rebin.
This PR does this. Non-PSD data now do not need to go through a `Calculate Projection` step (i.e. conversion to `MDEventWorkspace`). …

Non-PSD Mode

---

mslice/widgets/dataloader/dataloader.py

Adds various small features to the `DataLoader` widget:
* Only files loadable by MSlice (`nxs`, `nxspe`, `txt`, `xye`) are shown.
* Double clicking a file now loads it. (Double clicking a folder opens it as before).
* Pressing `Enter` on a file loads it, on a folder opens it.
* Pressing `Backspace` moves up a folder.
**To test:**
Code review.
Run MSlice and check the above functionality works as expected.
Fixes #273.

Dataloader usability fixes

---

mslice/presenters/data_loader_presenter.py
mslice/presenters/main_presenter.py

Avoids a bug by automatically selecting a workspace when it's loaded.
**To test:**
- Save a slice as 'slice1'
- Delete slice workspace
- Calculate projections from a different workspace and name this slice 'slice1' as well.
- Load original slice1 and overwrite.
- Slice1 should be automatically selected.
- Plot slice1 and check it displays correctly.
Fixes #235

Select and update loaded workspaces

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/plot_figure.py
mslice/presenters/data_loader_presenter.py
mslice/tests/data_loader_test.py
mslice/util/qt/QtGui.py
mslice/util/qt/QtWidgets.py
mslice/widgets/dataloader/dataloader.py
mslice/widgets/dataloader/inputdialog.py

A series of small bug fixes and improvements in advance of the beta release. Including:
* Fixes `pyqt` shim to handle `QPrinter` and `QPixmap` correctly for both `PyQt4` and `qtpy`.
* Add a title to cut windows.
* Now caches `Ef` for indirect `nxspe` files where we need to ask the user; also the "Apply to all" check box now works.
* Fixes an issue with setting the limits for `nxspe` indirect file, where it needs the `Ef` but is first run before this is asked from the user, meaning the limits dict entry is left blank.
**To test:**
* Load an indirect nxspe file, put 1.84 meV as Ef if using IRIS data (as in the zip below), and check you can plot slices / cuts / etc.
* Load another indirect nxspe and check that the Ef dialog comes up again with 1.84 meV this time.
* Load multiple indirect …

Pre-beta release bug fixes and improvements

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/slice/mantid_slice_algorithm.py
mslice/models/workspacemanager/mantid_workspace_provider.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/plot_window.ui
mslice/plotting/plot_window/slice_plot.py

Fixes a few small issues with interactive cuts:
* Cuts can now be made along the vertical as well as horizontal direction. This is determined by the shape of the initial rectangle. If it is "tall" (`x_width <= y_width`), a vertical cut is made. If it is "wide" (`x_width > y_width`), a horizontal cut is made.
* The step sizes along the cut direction is obtained from the parent workspace instead of being hard coded in.
* In non-PSD mode, it now detects correctly the axes to be integrated over for cuts along `DeltaE`.
In addition, a new feature - a `Flip Axis` button has been added which is only visible when in interactive cut mode. This allows the user to change the integration axis regardless of the original shape of the rectangle (e.g. plot a horizontal cut for a "tall" rectangle and vice …

Interactive cuts fixes

---

mslice/models/alg_workspace_ops.py

`_get_number_of_steps` rounded down, whereas the slice plotter rounds up. Now they both round up so they are consistent.
**To test:**
- Try changing the intensity option for different workspaces (e.g. `MAR22017_Ei10.00meV` was broken before) and check there are no errors.
Fixes #282

Fix intensity off-by-one broadcasting error 

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/plotting/plot_window/plot_figure.py

The plot background was stored on the `cut_plotter`, and its presence used to determine whether `create_cut` had been run yet. This is incorrect, as there is no one-to-one link between a `cut_plotter` object and the plot window.
This caused a bug where the `plot_handler` was not set, and some features could not be accessed.
The background is now accessed via methods on the `PlotFigureManager` and stored in the `plot_handler`.
**To test:**
- Plot a cut and hit keep
- Plot another cut
- Check the plot options can be accessed without error on both plots.
Fixes #281

Fix cut window missing plot_handler

---

mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py

A new `SlicePlot` object is created every time plot is clicked, but the `PlotFigureManager`is the same. This caused a situation where a new `SlicePlot` object was asked to replot a recoil line it had no knowledge of.
By moving `arbitrary_nuclei` and `cif_file` members to the `PlotFigureManager`, the necessary information to replot them is in the same place as the information about whether to display them or not.
**To test:**
- Plot a slice
- Overplot a recoil line of arbitrary mass and a cif file
- Close and re-plot slice
- Check there are no errors and they both reappear correctly.
Fixes #284

Move overplot members to PlotFigureManager

---

.travis.yml
mslice/app/__init__.py
mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/slice/matplotlib_slice_plotter.py
mslice/plotting/pyplot.py
mslice/util/__init__.py

Moves `check_mpl()` inside `show_gui` so it is always called to prevent errors on old matplotlib versions.
Fixes #291

Move check_mpl call

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/cut_plot_test.py
mslice/tests/quick_options_test.py
mslice/tests/slice_plot_test.py

Some quick_options tests were very basic because `plot_figure` could not be instantiated in the tests, but the `SlicePlot` and `CutPlot` objects bypass this requirement. 
Also adds some other tests to those related classes.
Fixes #224

Add more tests around quick options and plots

---

mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/labels.py
mslice/models/slice/matplotlib_slice_plotter.py

Moves axis labels and latex code into new `labels` module.
**To test:**
- check axis labels are still displayed correctly (on slices and cuts)
Fixes #293

Move common axis labelling code

---

mslice/models/slice/mantid_slice_algorithm.py
mslice/tests/slice_algorithm_test.py

Adds overdue tests for these calculations so it'll be easier to change this code in the future.

Add tests for intensity / recoil / powder line calculations

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure.py
mslice/plotting/plot_window/slice_plot.py

Prevents a bug when replotting a cut by clearing the figure when the plot window is closed. 
**To test:**
See issue 
Fixes #319

Clear cut figure when plot window is closed

---

mslice/models/workspacemanager/workspace_algorithms.py
mslice/tests/workspace_provider_test.py

Fixes a problem where `_combined workspaces` were incorrectly being treated as `non-PSD` because their `is_PSD` property wasn't set. This meant they couldn't be sliced.
**To test:**
- Load two `PSD` workspaces.
- Select both and click `calculate projection`
- Select both resulting event workspaces and click `Merge`
- Select resulting `_combined` workspace and click `display` to plot a slice.
Fixes #314

Fix error when displaying _combined workspaces

---

mslice/models/cut/cut_functions.py
mslice/models/cut/matplotlib_cut_plotter.py
mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_window.py
mslice/presenters/cut_presenter.py
mslice/tests/cut_presenter_test.py
mslice/widgets/cut/cut.py

Fixes some bugs with saving cuts.
**To test:**
1. Normal cuts
- Plot a cut 
- 'Save Cut to Workspace' button should **not** be visible
- Plotted cut should appear in `MD Histo` tab of workspace manager
- Click the save icon in the plot window and make sure the cut saves to a file correctly
- Close the plot, select the cut in the workspace manager and click save, make sure it saves correctly
2 . Interactive cuts
- Start an interactive cut
- The cut should **not** appear in the `MD Histo` tab until 'Save Cut to Workspace' is clicked
- Test 'Save Cut to Workspace' button works on both slice and cut window, causing the cut to appear in the `MD Histo` tab.
- Click the save icon in the plot window and make sure the cut saves to a file correctly
Fixes #332

Saving cuts bug fixes

---

scripts/mslice
scripts/mslice.bat

Allows developers to redefine the version of mantid used for mslice. 
**To test:**
```shell
./mslicedevel.sh
```
should still look for the nightly build.
Setting `MANTIDPATH` should use this version of Mantid, e.g.
```
MANTIDPATH=/media/data1/source/github/mantidproject/mantid-builds/nightly-py2/bin ./mslicedevel.sh
```
Fixes #338

Use MANTIDPATH to find mantidpython if set

---

mslice/plotting/plot_window/plot_figure_manager.py
mslice/presenters/workspace_manager_presenter.py

`BaseException.message` was used despite being deprecated, and this causes errors in Python 3. This PR changes these to `str(exception)` instead.
**To test:**
- Display 2D plot
- Click Save
- Select `.png` extension
- Check it saves as `.png` without errors.
Fixes #337

Fix exception when saving PNGs #337

---

mslice/models/axis.py
mslice/models/projection/powder/mantid_projection_calculator.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/slice_plotter_presenter.py
mslice/tests/cut_presenter_test.py
mslice/tests/slice_plotter_presenter_test.py
mslice/tests/workspace_provider_test.py

Previously, if a workspace had more than a thousand histograms, reading the `theta` values would be cut short to save time. This resulted in incorrect default Q limits. This PR removes this 'shortcut'.
Also tidied up some of the validation when entering slice values, so that the user gets meaningful error messages if a value is invalid. This is just a quick fix for now as there is already an issue to refactor this particular part of the code (#322).
**To test:**
See issue
Fixes #335

Improve default Q limits for large data sets

---

mslice/models/cut/cut.py
mslice/models/cut/cut_normalisation.py
mslice/models/slice/slice_functions.py
mslice/plotting/plot_window/cut_plot.py

Changes the behaviour of the `Norm to 1` option to using the (absolute) maximum value of the data rather than the range of the data as the normalisation factor.
The previous behaviour caused an implicit shift of the data, especially if there are negative values in the data.
Also fixes an issue where `Norm to 1` was applied to all cuts regardless of whether the option was checked or not.
**To test:**
Load any test dataset and make a cut. Check that when the `Norm to 1` option is checked the maximum value in the plot is `1` and if it is not checked that the cut for different values of the step size lie on top of each other (e.g. that the step size will not scale the data), and the value is different from `1`.
Also load this example file: …

Normalisation to unity

---

mslice/app/__init__.py
mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/models/cut/cut.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/workspace_manager_presenter.py
mslice/util/mantid.py
mslice/widgets/workspacemanager/command.py
mslice/workspace/histogram_workspace.py

Adds the ability to export a saved cut to the MantidPlot ADS, since now we do not store MSlice workspaces in the ADS, so they are not visible from MantidPlot.
**To test:**
Run MSlice within MantidPlot, and check that in the `MD Histo` tab there is a `Save to ADS` button (when running MSlice outside MantidPlot, this button should be hidden).
Load a dataset and make a cut. Then in the `MD Histo` tab click `Save to ADS`. Check that a `MatrixWorkspace` appears in the list of workspaces in MantidPlot. Plot this workspace and check that the values agree with that plotted in MSlice.
Check that the fitting interface works on this workspace.
Fixes #341

Export cut to MantidPlot ADS

---

mslice/presenters/data_loader_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/widgets/dataloader/dataloader.py

Attempting to `Load and merge` files of different formats would cause an error. This now displays a more helpful error message.
**To test:**
- Select multiple files
- If they have the same extension (e.g.`.nxs`) the `Load and Merge` button should work as normal.
- If they have different extensions, an error message should say files of different formats cannot be merged.
Fixes #342

Improve error when merging different file types on load

---

mslice/models/workspacemanager/workspace_algorithms.py

Fixes a bug where the value of `e_fixed` was not propagated to child workspaces after e.g. calculating projections. This causes the calculation of the powder lines to fail.
**To test:**
Load a PSD dataset (e.g. https://github.com/mantidproject/mslice/files/2201161/test_mslice_HYS.zip or MER30936_Ei10.00meV_one2one.nxs 
Calculate projection and plot the slice. Then plot a powder line from `Information`->`Bragg Peaks`. 
Fixes #347

E_fixed propagation

---

mslice/presenters/slice_plotter_presenter.py
mslice/widgets/slice/slice.py

Breaks up the `_display_slice` method and removes unused code.
**To test:**
- Test valid and invalid values in the slice dialog and make sure any displayed errors are correct.
Fixes #322

Tidy up SlicePlotterPresenter validation methods

---

mslice/models/cut/cut_functions.py
mslice/models/projection/powder/make_projection.py
mslice/models/projection/powder/mantid_projection_calculator.py
mslice/models/slice/slice_functions.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/slice_plotter_presenter.py
mslice/tests/slice_functions_test.py

The workspace passed into calculateProjection was being treated as a
workspace name when it might also be a workspace object. It now supports either.
Also fixes a problem when plotting multiple PSD workspaces #356 
**To test:**
```
ws = Load("...")
MakeProjection(ws, Axis1='|Q|', Axis2='DeltaE')
```
Fixes #353
Fixes #356

CLI - Fix workspace type error in MakeProjection

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_window.py
mslice/plotting/plot_window/slice_plot.py

Added functionality to deselect `interactive_cuts` when `cut_plot` window is closed.
**To test:**
Open up mslice
Load data then display it
Click interactive cuts and select a rectangle on the plot
When the cut window opens, close it
Observe that the `interactive_cuts` button in now deselected
Fixes #364

added functionality to close interactive cuts

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/plot_options.ui
mslice/plotting/plot_window/quick_options.py
mslice/presenters/cut_presenter.py
mslice/presenters/plot_options_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/tests/plot_options_presenter_test.py
mslice/tests/quick_options_test.py

Added functionality to hide error bars in the plot options menu and the quick options menu
**To test:**
Open up mslice 
Load some data
Perform a cut plot
1. Open up the plot options menu and uncheck/check the error bars options for the relevant plot
2. Double-click a plot and uncheck/check the error bars option for the plot
The error bars should now be hidden from the legend and the actual plot
Fixes #372

Hide error bars in cuts correctly

---

mslice/plotting/plot_window/interactive_cut.py

Added a `callback` method to redraw the rectangle selector whenever the canvas is redrawn.
**To test:**
Open mslice, perform a slice cut and an interactive cut, click the settings gear, click "Ok" and observe that the rectangle persists.
Fixes #285

#285 rectangle selector now persistent

---

mslice/plotting/globalfiguremanager.py
mslice/presenters/cut_plotter_presenter.py
mslice/views/cut_plotter.py

There was a bug caused by recent changes where a closed interactive cut that was labelled as 'current' would reopen again. This is because `plt.gcf()` was being called after the figure had been closed.
This checks if the figure still exists before calling `plt.gcf()`.
**To test:**
- Plot an interactive cut
- Turn interactive cuts mode off on the slice plot
- Mark the cut as 'keep'.
- Plot another interactive cut.
- Mark first plot window as make current.
- Move the rectangle and check that the current plot window is updated.
- Close the current cut window
- Close the kept cut window
- Check no cuts reopen automatically and interactive cuts is off.
_No associated issue_

Prevent closed interactive cut from reopening

---

mslice/widgets/workspacemanager/subtract_input_box.ui

Changed the subtraction ui to allow more decimal places in the spin box for the self shielding factor.
**To test:**
Load a workspace, click on `Subtract` and in the dialog which pops up, check that you can type a value into the spin box which has more than 2 decimal places - e.g. `0.12345`; click on one of the up or down buttons and check that this value increases/decreases in steps of 0.02 as before (and that the last digits are not truncated as long as the values are between `0` and `1`).
Fixes #373

Changed spin box to have more decimal places

---

mslice/app/__init__.py
mslice/plotting/plot_window/slice_plot.py

Cancelling the arbitrary_nuclei dialog leaves the option deselected. One can now only select integer values greater than zero. 
**To test:**
Perform a slice in mslice. Select "arbitrary nuclei" from the information -> recoil lines menu. Selecting cancel leaves the "arbitrary nuclei" options deselected. It is also only possible to choose integer values greater than 0.
Fixes #369 .

Fix issue with cancelling arbitrary nuclei user input

---

mslice/models/colors.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/colors_test.py
mslice/tests/quick_options_test.py
mslice/views/cut_plotter.py
mslice/views/slice_plotter.py

Mantid is upgrading matplotlib on Windows and this causes a few issues in mslice. This fixes
them in a backward compatible manner. For more information see the commit messages.
A few things to test:
* double-click overplot line on slice plot and check you can change the options
* double click on cut and do the same as above
* use the settings button on cut window to change line styles

Fix issues when running with matplotlib > 2.1

---

mslice/models/workspacemanager/workspace_provider.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/workspace_provider_test.py
mslice/tests/workspacemanager_presenter_test.py

The rename_workspace tests were moved to the workspace_provider_test.py file as they are now implemented there.
**To test:**
Fixes #362 .

moved rename_workspace tests to workspace_provider_test.py

---

mslice/app/mainwindow.py
mslice/plotting/plot_window/plot_figure_manager.py

The move window command now uses the screen centre to fix the position of cuts and slices
**To test:**
Open Mslice and plot a cut or slice. The windows open near the centre of the screen.
Fixes #418 .

Cuts and slices made to be repositioned with respect to the window center

---

mslice/cli/_mslice_commands.py
mslice/cli/helperfunctions.py
mslice/models/cut/cut.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/cut_widget_presenter.py
mslice/scripting/__init__.py
mslice/scripting/helperfunctions.py

Modified python script generation to account for multiple cuts from different workspaces.
**To test:**
Open Mslice. Load multiple workspaces. Using plot over, plot multiple cuts onto the same plot window. In the file options, click generate script.
Fixes #423 .

Script generations now accounts for multiple workspaces used in cuts

---

mslice/cli/_mslice_commands.py
mslice/widgets/ipythonconsole/ipython_widget.py

Changes the IPython console initialisation to not do `import *` on MSlice-wrapped algorithms if we are running in MantidPlot as this will overwrite the `simpleapi` versions of the algorithms in the base namespace (for all Python sessions, including the MantidPlot default IPython console and also the script windows). Instead if running in MantidPlot we import the MSlice-wrapped algorithms into `mslice.cli` and alias it to `mc`.
**To test:**
- Run MSlice in MantidPlot (copy the `mslice/mslice` folder to `<MantidInstall>/scripts/ExternalInterfaces`). 
- Start the MSlice interface.
- In a MantidPlot Python session load a workspace using e.g. `Load('MAR21335_Ei60.00meV.nxs', OutputWorkspace='ws')` - this should now work with MSlice master (because the MSlice `Load` now accepts …

Put mslice-wrapped Mantid algorithms into mslice.cli namespace

---

mslice/widgets/dataloader/dataloader.py
mslice/widgets/dataloader/dataloader.ui

Adds a button to the `Dataloader` widget to re-initialise the `QFileSystemModel` used in the files/directories table. The model is supposed to watch for changes to the filesystem (new files created / existing files removed / modified) and automatically update the `QTableView` showing the files but for some filesystems this sometimes does not work.
In particular there seems to be a problem with the network file system used at SNS where if a file is created by another user (e.g. by the autoreduce system) it sometimes does not show up in the `Dataloader` or in certain mounts where even new files created after MSlice is started by the current user is not seen - this is an intermittent problem and the exact underlying cause is still not known but seems to be OS related (it was only observed in …

Dataloader refresh

---

mslice/presenters/cut_plotter_presenter.py

This PR puts in some omitted lines which prevent the plotting of a saved cuts
**To test:**
1. Load a workspace and make a cut or several cuts (e.g. with the `width` parameter).
2. Click on the `MDHisto` workspace and select one of the saved cuts - click `Plot` and check that it plots ok (and also check that if no cut plot window exists that a new cut plot window appears). Click `Plot Over` and check that another curve is overplotted.
3. In the plot window select "File->Generate Script" and check that the generate python file accurately reproduces the plot.
Fixes #434

Fix plotting saved cuts bug

---

mslice/app/__init__.py
mslice/cli/_mslice_commands.py
mslice/tests/command_line_test.py
mslice/util/mantid/algorithm_wrapper.py
mslice/widgets/dataloader/dataloader.py
mslice/workspace/workspace_mixin.py

This PR fixes some minor bugs identified during user beta-testing as reported in #439
**To test:**
1. Run the following script (the datafile is in the MSlice dropbox folder) and checks that it runs without errors and produces the following workspaces: `MAR22012_Ei10.00meV`, `MAR22017_Ei10.00meV`, `MAR22017_sum`, `MAR22017_sum2`,  and a slice plot.
```python
import mslice.cli as mc
import mslice.plotting.pyplot as plt
import mslice.util.mantid.mantid_algorithms as s
ws1 = mc.Load(Filename='MAR22012_Ei10.00meV.nxspe+MAR22013_Ei10.00meV.nxspe', OutputWorkspace='MAR22012_Ei10.00meV')
ws2 = mc.Load(Filename='MAR22017_Ei10.00meV.nxspe', OutputWorkspace='MAR22017_Ei10.00meV')
ws3 = s.Plus(ws1, ws2, OutputWorkspace='MAR22017_sum')
ws4 = s.Plus(LHSWorkspace=ws1, RHSWorkspace=ws2, …
```

Minor bug fixes

---

mslice/cli/helperfunctions.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/presenters/cut_plotter_presenter.py
mslice/scripting/__init__.py
mslice/scripting/helperfunctions.py
mslice/tests/command_line_test.py
mslice/tests/cut_plotter_presenter_test.py

This is a small PR to fix some bugs identified during implementation of the energy units conversion framework - because the fixes here don't really fit into that work.
This PR fixes the first two issues mentioned in #443 (buttons doing nothing in the interactive cut window, and script generation getting things wrong if there are multiple cut windows and the user switches back and forth between them). The third issue cannot be addressed easily but the machinery for it is included in PR #442 (inclusion of MSlice `Axis` instances within `Workspaces` and using workspace comments to propagate them through Mantid algorithms). This is because the CLI does not really use the `CutPlotterPresenter` which is used by the GUI to cache cut information. So calls to cache cut information from the CLI …

Cut plotter bugsfixes

---

mslice/cli/_mslice_commands.py
mslice/models/workspacemanager/file_io.py
mslice/plotting/globalfiguremanager.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/workspace_manager_presenter.py
mslice/tests/command_line_test.py
mslice/tests/file_io_test.py
mslice/tests/slice_functions_test.py

This PR fixes several bugs identified in the unscripted testing for Mantid 4.0
It also fixes some issues with the unit testing on PyCharm in Windows (using Mantid 3.13) which seems to be sensitive to recursive import
**To test:**
1. Load a non-PSD workspace (e.g. `MAR21335_Ei60.00meV.nxspe`). Then change tab to `MDEvent` or `MDHisto`. Then change back to `2D` and click on the workspace name again. Check that it correctly disables the `Powder` tab and enables the `Slice` and `Cut` tabs.
2. Plot a slice from the loaded workspace. Got to `File`->`Generate Script`. In the file dialog, click `Cancel`. Check that no exception is raised.
3. In the slice window, click `Interactive Cut`. Draw a rectangular region in the slice and see that a cut window pops up. Click on `Interactive Cut` again to …

Minor bugs fixes

---

mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/plot_window.py

Adds a `Copy` button to plot windows which copies the plot image (bitmap only) to the system clipboard.
**To test:**
Make a slice and/or cut and then click on the `Copy` button on the toolbar (next to the `Save` button). Then go into another program which can handle images (e.g. GIMP, Paint, Word, LibreOffice) and paste the image - check that it's the correct image of the plot.
Fixes #452

Add image copy button to plots

---

mslice/models/cut/cut_algorithm.py
mslice/models/labels.py
mslice/models/slice/slice_functions.py
mslice/presenters/slice_plotter_presenter.py

This fixes a bug where the label for a 2-theta cut is `2Theta` rather than the expected `Degrees`. It seems that `MDWorkspaces` and `MatrixWorkspace` have different conventions: `MatrixWorkspace` expects `Degrees` which was what MSlice had but `MDWorkspace`s are more flexible and in the GUI in MSlice we call that axis `2Theta` which is then passed to the different algorithms which do not recognise this (they expect `Degrees`). 
This PR updates the relevant checks in the `Cut` and `Slice` algorithms so that they will now accept both `Degrees` and `2Theta`.
**To test:**
Repeat the cuts / slices detailed in issue #454 and check that they are correctly plotted now (e.g. `DeltaE` vs `2Theta` and `2Theta` vs `DeltaE` slices are consistent and cuts along `2Theta` work as described. Also check …

Fix 2theta units naming bug

---

mslice/models/cut/cut_algorithm.py
mslice/models/slice/slice_algorithm.py
mslice/models/slice/slice_functions.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/data_loader_presenter.py
mslice/tests/data_loader_test.py

Fixes bug in loading an indirect instrument `nxspe` file which prevented it from plotting
**To test:**
Load the nxspe file in [iris_reduced_data.zip](https://github.com/mantidproject/mslice/files/2945457/iris_reduced_data.zip) and check that you can plot slices and cuts from it.  
Fixes #451

Fixed bug to allow plotting indirect nxspe files

---

mslice/plotting/plot_window/plot_window.py

Mantid is moving away from using QtAwesome, so the reliance in msclice will no longer be possible. QtAwesome was replaced by a new mantid library dedicated to icons, for both C++ and Python. This has been used in it's place. The icons are very close if not identical to the previous icons.
**To test:**
- Open Mslice
- Load some data
- Get the data to the state in which a plot window can be opened
- Check out the new icons, including the interactive cut circular arrows (retweet) icon.

Migration from QtAwesome to get_icon

---

mslice/widgets/dataloader/dataloader.py
mslice/widgets/dataloader/dataloader.ui

I added a horizontal header to QTableView in the dataloader with the ability to sort items
**To test:**
Open MSlice
Observe that the horizontal header in not hidden
Click the arrow next to the column title to sort according to the title name
Click the arrow again for the reversed sorting order
Fixes #459 .

Add horizontal header to dataloader to allow sorting

---

mslice/workspace/workspace_mixin.py

Multiplication of workspaces and real numbers can now be done on a commutatively.
This was done by overloading the `__rmul__` operator.
**To test:**
Open Mslice
Load a workspace
Try to perform a workspace multiplication both ways (ws * 2 and 2 * ws)
Fixes #462 .

Left and Right multiplication of workspaces now work as expected

---

buildscripts/buildscript.sh
mslice/cli/_mslice_commands.py
mslice/models/cut/cut_algorithm.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/scripting/__init__.py
mslice/scripting/helperfunctions.py
mslice/tests/scripting_helperfunctions_test.py
mslice/tests/scripting_tests.py
mslice/tests/workspace_provider_test.py
mslice/util/mantid/algorithm_wrapper.py

Fixes a bug in the generation of a script from a workspace created by subtracting two other workspaces.
**To test:**
Download the datafiles here:  [subtract_bug.zip](https://github.com/mantidproject/mslice/files/2989165/subtract_bug.zip)). Load both datafiles, and subtract one from the other using the `Subtract` button. Plot a slice or cut of the subtracted workspace, and then save a script file from the plot (`File`->`Generate Script`). Run the generated file (`import <file>`) and check that it recreates the plot you generated from. 
In previous versions the subtracted file is not reference properly and running the generated script will give an error.
Fixes #458

Subtract script generation bugfix

---

mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/slice_plot.py

Disabled the `Save Cut to Workspace` button in the slice until an area has been selected by the rectangular select tool and a cut has been created.
**To test:**
Load a data file and `Display` a slice. Click on the `Interactive Cut` button on the plot window toolbar. Check that the `Save Cut to Workspace` button is not visible. Select an area with the rectangular select tool. Check that a separate cut plot window appears and that the `Save Cut to Workspace` button is now enabled.
Fixes #480

Disabled Save Cut to Workspace until area selected

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/quick_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/quick_options_presenter.py
mslice/tests/quick_options_test.py

Checks user input strings in the quick options label axes for invalid strings, and pop ups an error dialog if so. Previously MSlice would crash if the LaTeX string is invalid.
**To test:**
Plot a cut or slice. Click on one of the axes and input an invalid LaTeX string, e.g. `$\a$`. An error dialog should pop up and the label remains unchanged. Previously MSlice would crash.
Click on the settings (cogwheel) icon and change one of the axes to an invalid string. Check that an error dialog again pops up instead of MSlice crashing.
Fixes #483

Pop up error dialog on invalid LaTeX string

---

mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/views/cut_plotter.py

Fixes a but where only the first cut plotted on a window is saved.
**To test:**
Load data and make a cut. Click on the save icon in the cut window and save to a file. Make another cut, plot it (not plot over) and save that to a file also. Before this fix the two files are the same - and show the data from the first cut made. Now they should be different.
Make multiple (plot over) cuts on a single plot window. Click save. If you select a data file format (e.g. `ascii`) it will save multiple files for each cut, appending a serial number to the files to distinguish them.
Fixes #472

Fix cut saving bugs

---

mslice/widgets/slice/slice.py

Adds checks in the slice widget which forces one of the axes to be energy (`DeltaE`). Thus if the user tries to select two non-energy axes, the one which they did not just select will be switched to energy.
**To test:**
Load a workspace. In the slice tab, check that if you try to select both `2Theta` and `|Q|` as axes - it should switch which ever axis you did not select back to `DeltaE`.
Fixes #482

Restrict slices to always have DeltaE as an axis

---

docs/source/cli.rst

Fixes typos in example scripts in the documentation.
**To test:**
Code review. You can also locally build the documentation by going into the `docs/` folder and doing `make html` and then check the local html files in the `build/html` folder.
Fixes #485

Fixed errors in documentation

---

mslice/presenters/workspace_manager_presenter.py
mslice/tests/workspacemanager_presenter_test.py
mslice/util/mantid/algorithm_wrapper.py

Added unit tests to bring the workspace manager presenter coverage up.
Also changes the algorithm wrapper to check if the algorithm being wrap supports the `OutputWorkspace` property for the wrapping with `'__MSL'` name to hide within the ADS.
**To test:**
Code review and make sure the unit tests passes!
Fixes #474

Workspace manager unit tests

---

mslice/cli/helperfunctions.py

The check for `is_cut` introduced in PR 470 was incorrect and resulted in the base Matplotlib `errorbar` function being called on an MSlice cut object rather than the correct overloaded MSlice `errorbar` function, giving an error when trying to plot a cut from a PSD type data file (because the underlying workspace actually has two dimensions even though one has only one bin).
**To test:**
Load a PSD data set, make projection and then try to make a cut (either from the widget or an interactive cut). It should now work.
Fixes #493

Fix is_cut check

---

mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/cli/_mslice_commands.py
mslice/cli/plotfunctions.py
mslice/models/cut/cut.py
mslice/models/cut/cut_algorithm.py
mslice/models/cut/cut_functions.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/cut_widget_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/presenters/main_presenter.py
mslice/scripting/__init__.py
mslice/scripting/helperfunctions.py
mslice/tests/cut_widget_presenter_test.py
mslice/views/interfaces/mainview.py
mslice/workspace/histogram_workspace.py

Adds the option to make cut using the `Integration` algorithm in Mantid rather than the `Rebin2D` or `SofQW3` algorithms. The resulting cuts should be almost exactly the same as with the rebin algorithms for the same cut integration limits, differing only by an overall scale factor. However, cuts with larger integration limits should give larger signal with the `Integration` algorithm compared with the rebin algorithms because the rebin algorithms renormalise the data to account for the larger (integration) bin size.
There is now a new menu option in the main window - under `Options` -> `Cut algorithm`. The default is the original `Rebin` algorithm, but there is now an option to use the `Integration` algorithm. 
**To test:**
Load a workspace and make a cut using the original `Rebin` …

Integration option for cuts

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/plot_options.ui
mslice/plotting/plot_window/plot_window.py
mslice/plotting/plot_window/quick_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/plot_options_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/tests/quick_options_test.py

Changes the `QuickAxisOptions` and `PlotOptions` classes to be non-modal and to have a `Keep open` check box. If this is not checked the `Ok` button will close the dialog. If it is checked then `Ok` will submit the new values entered to the plot but the dialog will stay open. This is done by connecting the options dialog to both the update function in the presenter and the `_canvas.draw()` function of the plot window. When the `Ok` button is clicked, a Qt `Signal` is emitted to the presenter to update the model, and then another signal is emitted to the canvas to redraw the graph. (I think there is no guarantee that these signals will be processed one after the other so there may be a race condition but in testing this didn't not seem to be a problem and I did not want to add a time delay …

Keep dialog open

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_window.py
mslice/plotting/plot_window/slice_plot.py
mslice/scripting/__init__.py

Added a menu option to save the generated script to the system clipboard rather than a file
**To test:**
Load a dataset and make a plot. Click on File->Generate Script to Clipboard. Paste the result in a text editor and check that the script looks ok.
Fixes #499

Added menu option to save script to clipboard

---

mslice/models/cut/cut_algorithm.py
mslice/workspace/histogram_workspace.py

Changed code in `convert_to_matrix` to use wrapped MSlice versions of Mantid algorithms which does the workspace name conversions rather than using the Mantid `simpleapi` algorithms directly.
**To test:**
Run MSlice in MantidPlot or Workbench. Load data and make a cut. In the `MD Histo` tab click on `Save to MantidPlot` / `Save to Workbench`. The workspace should appear in the ADS.
Fixes #492

Fixed ads export bug

---

mslice/cli/_mslice_commands.py
mslice/presenters/data_loader_presenter.py
mslice/tests/command_line_test.py

When running a script in MantidPlot or the workbench it crashes either program on reloading data because of the popup dialog which asks if the user would like to overwrite a workspace. This PR changes the CLI code to avoid asking for the overwrite by explicitly _not_ overwriting the loaded workspace.
Whilst investigating this issue another issue ( #497 ) related to running a script was found.
**To test:**
Run MSlice through MantidPlot/Workbench, load a workspace and make a plot. Generate a script file and open it in the Python window. Run it (Ctrl+Enter) in that window and check that the plot is accurately created and MantidPlot/Workbench does not crash.
Fixes #464

Added override to avoid load overwrite dialog

---

mslice/models/workspacemanager/file_io.py
mslice/plotting/plot_window/plot_figure_manager.py

Fixed unhandled exception when user cancels the save dialog.
**To test:**
Plot a slice. Click the save icon and then cancel the dialog. Nothing should happen (previously lead to a crash).
Fixes #503

Fixed save dialog unhandled exception

---

mslice/util/mantid/algorithm_wrapper.py
mslice/workspace/histogram_workspace.py

Fixes a name collision which resulted in a `MatrixWorkspace` rather than a `MDHistoWorkspace` being passed to `errorbar` which meant that the non-MSlice overloaded `errorbar` function was being called leading to it not recognising a keyword argument and raising an unhandled exception which crashes MantidPlot/workbench.
**To test:**
Run MSlice in MantidPlot or workbench. Make a cut from the data and then in the `MD Histo` tab click on `Save to MantidPlot` / `Save to Workbench`. Then plot the same workspace - a plot should appear correctly.
Fixes #502

Plotting ads saved cuts bugfix

---

mslice/cli/__init__.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/util/qt/qapp.py

Forces the set_waterfall call to always happen in the thread that the QApplication object lives in. Allows scripts ran in the interpreters in both MantidPlot and MantidWorkbench to execute these scripts.
**To test:**
Try the steps described in the issue and MantidPlot or Workbench should not crash.
Fixes #504

Wrap set_waterfall to force a call in the qapp thread

---

mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py

Changes the `__del__` methods for the workspace wrapper classes to call `DeleteWorkspace` on associated mantid workspaces in the ADS if the workspaces are supposed to be temporary (`store=False` so the name has `_HIDDEN` appended).
**To test:**
Run MSlice inside the Workbench or MantidPlot and set the option to show hidden workspaces in the ADS. Make a slice and the activate `Interactive Cut` - move the selection box around - you should not see any `_HIDDEN` workspace appear in the ADS.
Click on `Save Workspace` in the cut window showing the interactive cut then close both the cut and slice windows. In the main MSlice window go to the `MD Histo` tab and checked that the workspace you saved is there. Plot it - it should show the same cut as you had last.
Fixes #512

Add __del__ method to workspace wrappers to delete temp ws

---

buildscripts/buildscript.sh
mslice/cli/plotfunctions.py
mslice/tests/command_line_test.py

Description of work
plotfunctions module was renamed to axesfunctions.
**To test:**
Any quick testing of slicing and cutting should now not produce an error.
To test the changes in a development version of Workbench:
* clone this repo and checkout this pull request branch
* assuming the mslice repo root is `<msliceroot>` then from the `mantid` build directory:
```
PYTHONPATH=<msliceroot> bin/workbench
```
Fixes #519

Fix calls to mantid.plots apis after changes

---

mslice/plotting/plot_window/plot_figure_manager.py

The `QPixmap.grabWidget` function in Qt4 was removed in Qt5 and it is recommended to use `QWidget.grab` instead. This change first tries the Qt5 version (for running in Workbench) and if that fails falls back on the Qt4 version (for running in MantidPlot).
**To test:**
Open MSlice in Workbench. Make a slice. Click on the **print** icon and click to print to a pdf. Click ok and check that the file dialog to select a pdf file name appears (instead of an error).
Fixes #521

Fixed obsolete grabWidget() function error in Qt5

---

mslice/util/mantid/mantid_algorithms.py

Adds a `try` block to check if the algorithm which MSlice is trying to wrap is a user defined algorithm (is not in the `simpleapi` namespace), and if so imports it directly.
**To test:**
*Before* starting MSlice, run the following script from the issue:
```py
from mantid.kernel import *
from mantid.api import *
class PrintNumber(PythonAlgorithm):
def PyInit(self):
self.declareProperty('Nsteps',1000)
def PyExec(self):
Nsteps = self.getProperty("Nsteps").value
print(Nsteps)
AlgorithmFactory.subscribe(PrintNumber)
```
Now start MSlice and check it starts. In the MSlice cli you should be able to type `PrintNumber(5)` or similar and get that output.
Fixes #516

Fixed user defined algorithm import bug

---

mslice/tests/histogram_workspace_test.py
mslice/workspace/histogram_workspace.py

In Python 3 dict.keys() returns a generator and cannot
be accessed like a list using an index. Instead
use the name of the first dimension and look up
the coordinates like this.
Added a unit test for this method that was missing.
**To test:**
See instructions in mantidproject/mantid#28173
Fixes #525

Fix indexing error into dict.keys generator

---

mslice/plotting/pyplot.py

Several changes to pyplot in matplotlib 3.2 need porting to mslice:
- Remove is_numlike usage
- Hardcode scale types in xscale/yscale docstrings
These are backwards compatible back to matplotlib 2.2
**To test:**
On Linux:
* Install the nightly package
* `python3 -m virtualenv -p /usr/bin/python3 --system-site-packages  ~/.virtualenvs/mpl32`
* `source ~/.virtualenvs/mpl32/bin/activate`
* `python -m pip install matplotlib`
* Start mslice: `PYTHONPATH=/opt/mantidnightly/lib:/opt/mantidnightly/bin:$PWD python scripts/start_mslice.py`.
Before these changes the errors in the referenced issue would stop mslice starting.
Fixes #529 .

Fixes for api changes in matplotlib 3.2.

---

mslice/util/mantid/_workspace_ops.py
mslice/util/mantid/init_mantid.py
mslice/workspace/base.py
mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py
mslice/workspace/workspace_mixin.py

Moved operator methods in WorkspaceMixin to new WorkspaceOperatorMixin
Wrap operators to Mantid internal API _do_binary_operation() function
Attach this operators to WorkspaceOperatorMixin when MSlice is imported
Split the `WorkspaceMixin` class into `WorkspaceMixin` and `WorkspaceOperatorMixin` where the overloaded arithmetic operators are now in `WorkspaceOperatorMixin`. Binary operators are not defined in this new mixin class directly but are instead wrapped at initialisation (when MSlice is imported) to use the Mantid internal API `_do_binary_operation` function. The unary operators `__neg__` and `__pow__` remain defined.
The wrapping of `_do_binary_operation` allows us to specify an output workspace name, since by the default using the (Mantid workspace) …

Properly wrap workspace arithmetic ops

---

.gitignore
mslice/plotting/globalfiguremanager.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/pyplot.py
mslice/tests/figure_manager_test.py
mslice/util/qt/qapp.py

This should be a more robust method for ensuring future updates of matplotlib don't introduce further calls that need to be forced onto the GUI thread when run from mantid's script editor.
**To test:**
Run any mslice script in the workbench script editor.
Fixes #535.

Force figuremanager calls to be on same thread as QApplication object

---

mslice/presenters/cut_widget_presenter.py

This PR fixes a crash on MSlice when attempting to overplot a cut which has different axes to the plot which is currently open.
**To test:**
1. Open Mslice and Load an appropriate file: [LET36360_1.05meV_rings.nxspe.zip](https://github.com/mantidproject/mslice/files/4792934/LET36360_1.05meV_rings.nxspe.zip)
2. Under Workspace Manager > 2D > select the loaded data 
3. Under the Cut tab, select
along `DeltaE` from 0 to 1, 
over`Q` from 0 to 1 
and click `Plot` to plot this Energy cut
4. Now change it to 
along `Q` from 0 to 1
over `DeltaE` from 0 to 1 
this time clicking `Plot Over`.
5. There should be no crash. Instead a red error message will appear at the bottom of the MSlice GUI.
**Release notes** will be added in a separate mantid repo PR
Fixes #534

MSlice - fix overplot crash when plots have different axes

---

mslice/presenters/workspace_manager_presenter.py
mslice/widgets/workspacemanager/workspacemanager.py

Fixes crashes associated with the rename workpsace and add workspace dialogs when the user clicked cancel. This was fixed by raising `RuntimeErrors` when the dialogs were cancelled, which are caught by the `workspace_manager_presenter`.
**To test:**
1. Load a workspace, e.g. `164198.nxs` in `TrainingCourseData`
2. In the Workspace Manager tab, click add. 
3. Cancel the dialog, check MSlice doesn't crash.
4. Repeat for rename workspace.
Fixes #542

Prevent crashes on cancel for rename- and add-workspace dialogs

---

mslice/plotting/plot_window/plot_window.py
mslice/util/qt/validator_helper.py
mslice/widgets/cut/cut.py
mslice/widgets/slice/slice.py
mslice/widgets/workspacemanager/input_boxes.py

Fixes the possibility of a crash by restricting the input of the line edits used for entering doubles. 
By default, a `QDoubleValidator` allows the entry of a comma. This will cause a crash when attempting to convert the entered data to a float. This PR prevents the entry of comma's into the relevant line edits thereby preventing a crash.
**To test:**
2. Load any data (e.g. `MAR25087`)
3. Go to the `Workspace Manager` tab
4. Click the down arrow next to `Compose` and select `Scale`
5. Attempt to enter a comma into the line edit. This should not be allowed.
6. Also try to enter a comma into the line edits seen on the `Slice` and `Cut` tabs. This should not be allowed.
Fixes #551.

Prevent MSlice crash by stopping the entry of comma's into QLineEdits expecting double's

---

mslice/presenters/workspace_manager_presenter.py

Fixed bug that only one workspace can be selected from the workspace panel so the Add Workspace dialog had to be used to select additional workspaces. Now the Add Workspace dialog only opens when one workspace was selected from the workspace panel. In case of a selection of more than one workspace clicking the Add button is enough to add the selected workspaces.
**To test:**
2. Load any data
4. Select more than one workspace
5. Click on Add
6. Check that new workspace with suffix '_sum' is created without opening the Add Workspace dialog
Fixes [#559](https://github.com/mantidproject/mslice/issues/559)

Allow selection of more than one workspace for addition in workspace panel of MSlice

---

mslice/models/cut/cut.py

Modified width function to not accept negative values or a standalone 'e'. Double values in proper e notation are still allowed.
**To test:**
2. Load any data
4. Click on the Cut tab
5. Attempt to enter a negative value into the width box. 
6. Also try to enter a standalone 'e' into the width box.
Fixes [#556](https://github.com/mantidproject/mslice/issues/556)

Fixed MSlice crash when entering unexpected values into width box

---

mslice/widgets/workspacemanager/input_boxes.py

The Subtract Workspace dialog selects the first workspace by default but failed to use it. This resulted in crashes. This is fixed now.
**To test:**
2. Load any data
4. Select a workspace
5. Click on Subtract
6. In the Subtract Workspace dialog click on Ok
Fixes [#560](https://github.com/mantidproject/mslice/issues/560)

Fixed MSlice crashes when not manually selecting a second workspace for subtracting

---

mslice/widgets/workspacemanager/input_boxes.py

Subtraction of one workspace from another did not result in the expected workspace in MSlice
Modified user_input function in input_boxes.py to return the workspace selected by the user as the background workspace.
**To test:**
1. Open MSlice in IDAaaS
2. Load two datasets that result in compatible workspaces
4. Scale the first workspace with a random scale factor
5. Select the second workspace
6. Click on Subtract
7. Select the scaled workspace
8. Ensure that the subtracted workspace uses the scaled workspace as the background workspace
Fixes [#576](https://github.com/mantidproject/mslice/issues/576).

Fixed bug that overwrote selection of background workspace when subtracting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md

Added two new issue templates for MSlice.
**To test:**
Code review. Check the wording of the new bug report template.
This does not require release notes because **it is an internal process change.**

Move MSlice issue templates to new GitHub system

---

mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py

Occasionally temporary workspaces are already deleted when the clean up function is called. If not caught this causes runtime errors.
Now there is a check if the respective workspace is still present.
**To test:**
2. Load any data
4. Select a workspace
5. Click on Subtract
6. In the Subtract Workspace dialog click on Ok
7. Select the initial workspace once more
8. Click on Subtract
9. In the Subtract Workspace dialog click on Ok
Fixes [#528](https://github.com/mantidproject/mslice/issues/528)

Fixed runtime error when trying to delete workspace for the second time

---

mslice/plotting/plot_window/plot_options.py

Adding curves via Python script with colors that are not in the pre-defined color list caused an unhandled exception.
Now these additional colors are temporarily added to the color list used in settings.
**To test:**
Follow instructions in issue description.
Fixes [#550](https://github.com/mantidproject/mslice/issues/550)

Fix for colorcycle problem for multiple curves on one plot

---

.github/workflows/unittest.yml
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/pyplot.py
mslice/tests/figure_manager_test.py

The pyplot-like API for MSlice now allows closing plot windows with the close('all') command. 
**To test:**
Via the command line interface of MSlice, open several plot windows. Use close('all') to close all of them.
Fixes #[536](https://github.com/mantidproject/mslice/issues/536).

536 close all feature

---

.github/workflows/unittest.yml
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py
mslice/presenters/plot_options_presenter.py
mslice/tests/plot_options_presenter_test.py

Added a 'Delete Line' button in the settings dialog for 1D plots. Clicking it removes the LegendAndLineOptionsSetter widget for the respective line as well as the corresponding line in the cut plot.
**To test:**
1. Open a cut plot with several lines.
2. Open the settings dialog from the plot window.
3. Delete one of the lines.
4. Check that the corresponding settings widget is removed from the settings dialog.
5. Check that the corresponding line and its legend is removed from the plot.
Fixes #[549](https://github.com/mantidproject/mslice/issues/549).

549 delete curve feature

---

mslice/models/slice/slice_functions.py
mslice/models/units.py
mslice/plotting/plot_window/slice_plot.py

Mslice crashed often when converting Intensity from S(Q,E) to GDOS. One of the problems are unexpected input values.
Also, temperature input in Kelvin will not always have the unit appended. This fix allows both values with and without unit.
When selecting a pre-configured setting for GDOS, for instance 'MSlice', this also often resulted in crashes whenever there is no valid entry for temperature. 
- When entering an invalid temperature an error message is displayed. 
- The function trying to convert an input value with or without 'K' as a unit is more robust now (get_sample_temperature_from_string).
- Selecting a pre-configured setting for GDOS that does not have a valid temperature now throws the exception 'sample temperature not found' instead of crashing MSlice.
**To test:**
1. Open …

Added exception handling for different input values for GDOS to prevent MSlice crashes.

---

mslice/scripting/__init__.py

Export correct output workspace handles to script
**To test:**
[IrisData.zip](https://github.com/mantidproject/mslice/files/6277713/IrisData.zip)
-> Download "IrisData.zip" and Extract it
-> Open Mantid Workbench
-> Click "Interfaces/Direct/MSlice" (at the top-left corner)
-> Navigate to the above extracted "IrisData" folder
-> Select one of the files and click "Load Data"
-> An input dialog box titled "Indirect Ef" will appear
-> Input a float value (let's say 1.84)
-> Click "OK"
-> Choose "Scale" algorithm from the "Compose" options
-> An input dialog box titled "Scale parameters" will appear
-> Input a float value for scale factor (let's say 0.9)
-> Click "OK"
-> Choose "Subtract" algorithm
-> A dialog box appears asking to select a workspace to be subtracted
-> Select second workspace …

Export correct output workspace_handles to script

---

mslice/presenters/data_loader_presenter.py

When multiple Indirect related workspaces are loaded and ef_defined is False,
an input dialog box appears to take Efixed value and user may want to apply 
the same Efixed value for all other loaded workspaces by checking apply to all
workspaces. 
Before this fix, for the first workspace following three operations are applied 
workspace_handle.e_fixed = fixed_final_energy
workspace_handle.raw_ws.run().addProperty('Efix', fixed_final_energy, True)
get_limits(workspace_name, 'DeltaE')  # Necessary to process the limits
and for the remaining workspaces only the first operation of the above three is applied.
Now, all three operations are applied for all the workspaces that are loaded together
if the user checks the "Apply to all workspaces" after entering an input value …

Apply input fixed final energy to all workspaces if user wants so

---

mslice/cli/helperfunctions.py
mslice/plotting/plot_window/cut_plot.py
mslice/scripting/helperfunctions.py

While exporting to a script, the information regarding hidden cuts is lost and the cuts were being shown despite they were hidden. This fix adds the missing information to script and keeps the hidden cuts hidden even while using the exported script.
**To test:**
[hide_curves_start_script.txt](https://github.com/mantidproject/mslice/files/6272766/hide_curves_start_script.txt)
-> Update 'SET_CORRECT_PATH_TO_BUILD_PARENT' to parent directory of build directory in the attached 'hide_curves_start_script.txt'
-> Copy the python script from hide_curves_start_script.txt (make sure the above step is done to be able to read the input file correctly) and paste it in Mantid Workbench Jupyter IPython Console and Enter
-> Matplotlib figure with four lines and legends should show …

Keep hidden cuts hidden while using exported script

---

mslice/app/__init__.py
mslice/app/mainwindow.py

Implements floating/ontop window behaviour (that can be set in workbench settings) on mslice, as described in [this PR on the mantid repo](https://github.com/mantidproject/mantid/pull/30129).
**To test:**
- Launch mslice and check it opens correctly, and that without mantid the window is 'floating'.
- If possible, test the behaviour in workbench. "Floating" means that mslice would disappear behind the workbench window when the user changes the window in focus. "On top" means mslice would stay on top of workbench.

Implement floating/ontop window behaviour for mslice

---

docs/source/cli.rst
docs/source/quickstart.rst

**To test:**
MantidPlot should not be mentioned anymore in the MSlice documentation.
Fixes #[605](https://github.com/mantidproject/mslice/issues/605).

Replace MantidPlot with MantidWorkbench in documentation

---

mslice/plotting/globalfiguremanager.py
mslice/plotting/plot_window/plot_window.py

There are two fixes combined in here:
1. When displaying an empty plot window the AttributeError when calling save_default_options() without having a Cut or Slice window is caught.
2. When destroying a plot window that is neither Cut nor Slice window this window is removed from _unclassified_figures but not treated as a plot window with a category which would cause an exception and crash Mantid.
**To test:**
Use data and script from original issue: https://github.com/mantidproject/mslice/issues/610 and the current beta version from Mantid (with Mantid 6.0 this will be masked by a different bug).
Fixes #[610](https://github.com/mantidproject/mslice/issues/610).

Fixes problems for empty plots

---

mslice/plotting/plot_window/cut_plot.py

When a `cut plot` is requested via the `plotover` option on an existing plot window, this fix brings the `plot window` to the top if it was minimized or forward if it was in the background.
The fix is inspired by
https://github.com/mantidproject/mslice/blob/33239062a80caf9d61f2b8167f9551e8b8768f82/mslice/plotting/plot_window/plot_figure_manager.py#L55-L58
**To test:**
-> Make a cut plot using `MSlice`
-> Minimize the above cut plot window (or bring forward some other window so that the plot window goes to the background)
-> Plot another cut using the plotover option 
-> Check if the plot window raises to the top if it was minimized or comes forward if it was in the background
Fixes #612.

Raise or bring forward plot window for plotover

---

.github/workflows/onlinedocupdate.yml
docs/source/conf.py
mslice/__init__.py

The gh-pages branch is used to populate https://mantidproject.github.io/mslice/ 
For this the *.rst files in docs have to be converted into html using Sphinx.
The work included
- Updating the MSlice version number
- Updating the Sphinx configuration file conf.py
- Adding a GitHub workflow to run Sphinx automatically whenever the MSlice version number is updated and push the html docs to the gh-pages branch
**To test:**
Please note that the new Github workflow can only be tested once this PR is merged into master.
To test the first two changes install Sphinx locally (`pip install -U sphinx`) and run `make html` in the docs folder of mslice.
Fixes #[617](https://github.com/mantidproject/mslice/issues/617).

Updated online documentation and added Github workflow for this

---

mslice/util/mantid/algorithm_wrapper.py

Resulting workspace is wrapped 
https://github.com/mantidproject/mslice/blob/c817c9ee255f33eb8ba05b714f0d52bc10be4ac3/mslice/util/mantid/algorithm_wrapper.py#L68-L69
conditionally based on the instance of input_workspace returned by _parse_ws_names . https://github.com/mantidproject/mslice/blob/c817c9ee255f33eb8ba05b714f0d52bc10be4ac3/mslice/util/mantid/algorithm_wrapper.py#L14
https://github.com/mantidproject/mslice/blob/c817c9ee255f33eb8ba05b714f0d52bc10be4ac3/mslice/util/mantid/algorithm_wrapper.py#L36
For this reason, if the workspace is provided through its name, the corresponding workspace_handle was not acquired and the rewrap of the result has been ignored. 
In this fix, if the workspace_name is provided, its handle is acquired using get_workspace_handle …

Pickup workspace from its name and rewrap the resulting workspace

---

.github/workflows/onlinedocupdate.yml
mslice/__init__.py

The workflow for the html doc update needed a minor update as sphinx could not find the documentation source code. This is fixed now and after a successful test https://mantidproject.github.io/mslice/ is updated to the current MSlice version in development.
**To Test**
https://mantidproject.github.io/mslice/ should have the version number "2.3.0.dev "

Minor modification to workflow for html doc update

---

mslice/views/slice_plotter.py

Let say over-plots lines are plotted on an existing slice plot and then
the slice plot is re-plotted on the same plot window.
Previously plotted (checked) over-plot lines do not appear on the new slice plot.
This fix plots previously over-plotted lines on the re-plotted slice.
**To test:**
--> Plot a slice of a workspace (using Display)
--> Over-plot lines using Information/ recoil lines (or) Bragg  peaks from the menu
--> Re-plot slice (using Display)
--> Without this fix, only the slice would appear when re-plotted
--> With this fix, all the previously over-plotted lines should also appear when the slice is re-plotted
Fixes #515.

Restore checked over-plot lines on a re-plotted slice

---

mslice/models/cut/cut.py
mslice/models/labels.py
mslice/models/powder/powder_functions.py
mslice/models/slice/slice_functions.py
mslice/models/units.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/overplot_interface.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/tests/slice_functions_test.py
mslice/tests/slice_plot_test.py
mslice/views/slice_plotter.py

Powder(Bragg) peaks are enabled on cut plots in addition to slice plots. 
Overplot interface is created taking material from powder peaks implementation for slice plots.
**To test:**
Create a slice plot
Make sure Information over-plots on slice plots work without any problems (The existing feature is not corrupted)
Create a cut plot
Then check that powder(Bragg) peaks (in Information) can be invoked on a cut plot
Fixes #602 .

Enable powder(Bragg) peaks on cut plots

---

mslice/app/mainwindow.ui

Changed the default tab from plot to load.
**To test:**
Open MSlice and make sure that the load tab is opened and not the plot tab.
Fixes #[629](https://github.com/mantidproject/mslice/issues/629).

Changed default tab to load tab

---

mslice/views/cut_plotter.py

Without saving the default options for cut plots scripts cannot be generated successfully.
**To test:**
Create cut plot. On the plot window, click File->Generate Script to Clipboard
Fixes #[628](https://github.com/mantidproject/mslice/issues/628).

Save default options for cut plot

---

mslice/cli/__init__.py
mslice/cli/helperfunctions.py
mslice/workspace/helperfunctions.py
mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py

In the MSlice matplotlib projection the matplotlib errorbar method should only be used when args[0] is not a HistogramWorkspace as otherwise parameters are either unknown or unsuitable (issue https://github.com/mantidproject/mslice/issues/626).
Another error occurred when trying to delete the same workspace twice. This problem was also described in https://github.com/mantidproject/mslice/issues/544. The solution is to handle the exception this causes.
**To test:**
Follow the instructions in https://github.com/mantidproject/mslice/issues/626 and https://github.com/mantidproject/mslice/issues/544. The described errors should not appear anymore.
Fixes #[626](https://github.com/mantidproject/mslice/issues/626) and #[544](https://github.com/mantidproject/mslice/issues/544).

Fix for errors caused by small interactive cuts

---

mslice/presenters/cut_plotter_presenter.py

Added exception to prevent crash when trying to display a Bragg peak when there is no Bragg peak in the data.
**To test:**
Follow the steps described in https://github.com/mantidproject/mslice/issues/627. Instead of a crash there is a warning 'No Bragg peak found.'
Fixes #[627](https://github.com/mantidproject/mslice/issues/627).

Added exception for bragg peak not found

---

mslice/scripting/__init__.py

Pasting generated scripts did not work on Linux. One part of the problem is that Ctrl +v does sometimes not work as expected on Linux. By using QtGui.QGuiApplication with clipboard mode instead of QtWidgets.QApplication it is at least possible to ensure that both shift insert as well as right clicking and selecting 'Paste' can be used.
**To test:**
1. Open MSlice
2. Load data
3. Plot a slice
4. On the plot select "generate script to clipboard"
5. Paste script to script editor either with shift insert or with a right click and 'Paste'
Fixes #[630](https://github.com/mantidproject/mslice/issues/630).

Improve clipboard usage for scripts

---

.github/workflows/onlinedocupdate.yml

Previously the online documentation for MSlice was only updated after a change in 'mslice\__init__.py' in main branch. 
This is now changed to every push to the main branch.
For some actions in this workflow there was no version number specified but 'master' used as a default. Now all actions have version numbers.
**To test:**
Once this PR is merged into main, the online documentation should have the version number 2.3.0 instead of the current 2.3.0.dev. Unfortunately this is not visible beforehand.

Updated workflow for automatic doc update

---

.github/workflows/conda.yml
.github/workflows/onlinedocupdate.yml
.github/workflows/unittest.yml

This PR fixes four issues in the MSlice GitHub workflows:
1. Use https instead of http for sourceforge.net
2. The path to the Mantid nightly builds on sourceforge.net is slightly different now
3. The path to the file with information on the Mantid nightly release on GitHub has changed: main instead of master
4. The version number of sphinx-notes/pages is 1.0 and not v1
Issue 1. - 3. are the reason why the workflows for nightly builds of MSlice as well as for any push to a branch that is not workflow_fix_file_path fail at the moment.
**To Test**
For 1.-3. check in the Action tab whether the workflow for the push to workflow_fix_file_path was running successfully.

Minor bug fixes for GitHub workflows

---

mslice/cli/plotfunctions.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/tests/cli_mslice_projection_test.py

This bug fix has to elements. The plot figure manager was updated to draw the canvas in the show method to ensure that the figure is visible. This bug was originally discovered for slice plots but occurred for both slice and cut plots.
The second element is removing the matplotlib pchanged call that activated the callback on_newplot for cut plots as this caused crashes. Now on_newplot is called directly for cut plots.
**To test:**
1. In the Workspace Manager tab of the MSlice interface load a data set (MAR21335_Ei60meV) and select the workspace 
2. Click Display in the Slice tab without changing the default values
3. Navigate to the File menu on the slice plot
4. Select Generate Script to Clipboard and paste the script into the Mantid editor.
5. Close the window with the slice plot
6. Run …

Fix for empty window in generated script

---

mslice/plotting/plot_window/plot_figure_manager.py

A quick fix to the imports for `QPrinter` and `QPrintDialog` because the module had changed from `QtWidgets` in QtPy4 when the code was originally written to `QtPrintSupport` in `qtpy` which we're using now.
**To test:**
Plot a cut, and click on the printer icon - it should show up a dialog. 
Print to a pdf - a file should be generated.
Previously it gave an `AttributeError`.
Fixes #657

Fix print button import error

---

mslice/cli/__init__.py
mslice/cli/helperfunctions.py
mslice/scripting/helperfunctions.py
mslice/tests/cli_helper_functions_test.py
mslice/tests/scripting_helperfunctions_test.py

Added functionality to store information on Bragg peaks for cut plots during script generation. Also, added functionality to reproduce cut plot by running the script.
For testing follow instructions in issue.
Fixes #648.

Fixed bug that prevented script generation for cut plots

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/slice_plot.py

When a plot is created by running a script generated from a plot the default options are not saved. This caused an exception when trying a to generate a new script from the plot. Now not existing default options are treated as unchanged options.
**To test:**
Follow instructions in original issue. Please note that this has been fixed both for slice and cut plots.
Fixes #652.

Prevent exception when generating script from plot from script

---

mslice/widgets/dataloader/dataloader.py

MSlice does not allow to load a file by entering the file path and name into the file path box on top of the data loader tab. In order to differentiate this case from entering an invalid file path a new error message was added: "Loading by file path is not supported"
**To test:**
Enter the full path to a file with the filename into the box on top of the data loader tab, e.g. C:\data\MAR21335_Ei60meV.nxs and hit enter
Fixes #671.

Added error message when attempting to load by file path

---

mslice/util/mantid/algorithm_wrapper.py

The fix for the bug https://github.com/mantidproject/mslice/issues/531 included returning workspace handles for all input workspaces that are provided by the workspace name. This caused problems when using the Scale button on Mslice. By being more selective when to return a workspace handle the original fix still works and the Scale button is usable again as well.
**To test:**
1. In the Workspace Manager tab select the workspace MAR21335_Ei60meV
2. Click on the Scale button
3. Click ok on the pop up window. Check that no exception is thrown.
Also quickly check if https://github.com/mantidproject/mslice/issues/531 is still fixed. 
Fixes #649.

Fixed bug in processing of input workspaces

---

mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/slice_plot_test.py

Added ability to add/toggle legends on Slice Plots with regards to recoil lines/bragg peaks. Added unit test to confirm that legend is added when update_legend() is called.
**To test:**
1) Open MSlice (Interfaces > Direct > MSlice)
2) Use file browser on data loading tab to load appropriate data (MAR21335_Ei60meV used)
3) Click display on slice sub-tab on Workspace Manager tab.
4) Add a [number of] recoil line /brag peaks to plot that is generated.
4) Observe legend appearing automatically and updating with each added feature, as legends are set to automatically show.
5) Toggle Legends off/on using the toolbar, observe legend being added/removed appropraitely.
Fixes #651.

Added legends for recoil lines/bragg peaks on Slice Plots

---

mslice/__init__.py
mslice/widgets/cut/cut.py

Removed automatic scaling to meV of cut parameters when changing workspaces. 
For testing please follow the instructions in the original issue.
Please note that this bug is not covered in a unit test but will be included as a test in the manual testing instructions.
Fixes #665.

Fixed default units for cuts when using several workspaces

---

environment.yml

For some reason nose did not get installed properly anymore for GitHub workflows. By using pip instead of conda for installing nose this problem is fixed.

Replace conda nose with pip nose

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py

Removed the Delete Line button from the edit line dialog.
**To test:**
1. In the Workspace Manager tab select the workspace MAR21335_Ei60meV
2. Navigate to the Cut tab
3. In the row labelled along, set the from value to 0 and the to value to 10
4. In the row labelled over, set the from value to -5 and the to value to 5
5. Click Plot. A new window with a cut plot should open.
6. Double click on the line. A line editor should open.
7. Check that there is no Delete Line button
Fixes #674.

Removed delete line button for quick options dialog

---

.github/ISSUE_TEMPLATE/bug_report.md
environment.yml

The bug template now asks for the MSlice version instead of the Mantid version. In addition, it automatically adds the 'bug' label.
**To test:**
Check the changes to the bug_report.md file.
Fixes #650.

Changed Mantid into MSlice and added bug label

---

mslice/cli/helperfunctions.py
mslice/models/workspacemanager/workspace_algorithms.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/presenters/slice_widget_presenter.py
mslice/quickview/workspace_manager_quickview.py
mslice/tests/cli_mslice_projection_test.py
mslice/tests/command_line_test.py
mslice/tests/pixel_workspace_test.py
mslice/tests/slice_functions_test.py
mslice/tests/slice_plotter_presenter_test.py
mslice/tests/workspace_test.py

To clean up the code a bit some of the imports were moved to the top of their respective files. Unfortunately it is not possible to move all imports in this way as it causes problems with circular dependencies.
**To test:**
Check that tests are still passing.
Fixes #645.

Moved some imports to top

---

.github/workflows/onlinedocupdate.yml

Adds installation of `texlive` so that equations in the documentation (particularly [here](https://mantidproject.github.io/mslice/slicing.html#converting-intensity-information-in-displayed-data)) work.
**To test:**
Make sure all CI tasks run and equations are displayed correctly in the online docs.
----
No issues.

Add latex installation in doc build action

---

docs/source/quickstart.rst
environment.yml
mslice/app/mainwindow.ui
mslice/presenters/cut_plotter_presenter.py
mslice/tests/cut_plotter_presenter_test.py
mslice/widgets/cut/cut.py
mslice/widgets/cut/cut.ui

The `Save to Workspace` button on the cut tab is now called `Save to Workbench` and does save the corresponding MD Histo workspace to the ADS. In addition, the `Save to Workbench` button on the MD Histo tab was resized so that the button text is fully visible. The documentation was updated with details on the  `Save to Workbench` buttons and the `Save Cut to Workspace` button.
**To test:**
Check spelling and grammar of the documentation changes. Try out the  `Save to Workbench` button for a cut.
Fixes #673.

Fixed save to workspace button

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_window.py
mslice/plotting/plot_window/slice_plot.py

Disabled some of the menu items and buttons on the MSlice plot window to allow plotting of data not from an MSlice workspace, for instance arrays.
The bar now only contains buttons for zoom in, zoom out, Keep, Make Current, Copy and Print. The menus for Information and Intensity are visible but disabled. The menu File only has the entry Close.
**To test:**
Run the script from the initial issue.
Fixes 686.

Changed default visibility for various menu items

---

.github/workflows/conda.yml
.github/workflows/unittest.yml
mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/presenters/cut_widget_presenter.py
mslice/presenters/interfaces/main_presenter.py
mslice/presenters/main_presenter.py
mslice/presenters/presenter_utility.py
mslice/tests/cut_widget_presenter_test.py
mslice/tests/main_presenter_test.py
mslice/views/interfaces/cut_view.py
mslice/widgets/cut/cut.py
mslice/widgets/cut/cut.ui
tools/boilerplate.py

The cut algorithm names were misleading and easily overlooked as only available as a global setting in the main menu.
The displayed names are now updated and the cut tab has a combo box to select the cut algorithm individually (using the previously unused slot for the Smooth input ). The logic behind this is the same as for the energy units. The global setting changes the current workspace and every new workspace, previous workspaces remember their setting.
**To test:**
Check both global and local cut algorithm settings.
The documentation is not yet updated to reflect this and will be updated as part of #689.
Fixes #687.

Update cut algorithm names and added combo box on cut tab

---

mslice/plotting/pyplot.py

MSlice has a version of `pyplot.py` from Matplotlib in order to provide a similar command line interface - this was copied almost verbatim from Matplotlib 1.5 and was updated to Matplotlib 2 several years ago. Since then Matplotlib 3 has been released which has removed the deprecated `hold` option and this now causes non-MSlice plotting to fail.
This change is just to check if the hold feature is present or not and if not to not crash due to an `AttributeError`. 
A more long lasting fix is to refactor the `pyplot.py` file to import from the underlying Matplotlib `pyplot` instead of copying its contents as described in issue #693
**To test:**
Run the script in issue #686 with a Matplotlib 3 installation and check that it does not error and a sine curve is plotted.
Fixes #686

Pyplot update

---

mslice/models/cut/cut_algorithm.py
mslice/tests/command_line_test.py
mslice/workspace/histo_mixin.py

This PR adds the option to run the `Cut` algorithm with an "Integration" (summed counts) method.
**To test:**
The test file (125MB) is on the `\\Olympic\Babylon` shared drive accessible in ISIS.
Run the following script:
```python
import mslice.cli as mc
import mslice.plotting.pyplot as plt
LET73024_1to1_3_70 = mc.Load(Filename=r'\\Olympic\Babylon5\Public\duc\Ross nxspe files\LET73024_1to1_3.70.nxs', OutputWorkspace='LET73024_1to1_3.70')
ws_LET73024_1to1_3_70_QE = mc.MakeProjection(InputWorkspace=LET73024_1to1_3_70, Axis1='|Q|', Axis2='DeltaE')
fig = plt.gcf()
fig.clf()
ax = fig.add_subplot(111, projection="mslice")
algo = 'Integration'
for intrng in [0.5, 1, 2]:
cut = mc.Cut(ws_LET73024_1to1_3_70_QE, CutAxis="|Q|,0.0,2.0,0.01166", IntegrationAxis=f"DeltaE,-{intrng},{intrng},0.0", …
```

Add "sum" option to PSD Cut

---

docs/source/quickstart.rst

Updated section 1.1 in the Quick Start menu with description on how to change the font size of the main GUI.
**To test:**
Please check spelling and grammar of the new text and whether these new instructions make sense.
Fixes #554.

Added comment in doc about font size changes

---

docs/source/cutting.rst

Added information on how to save MD Histo workspaces to Mantid workbench.
**To test:**
Please check spelling and grammar of the new text and whether these new instructions make sense.
Fixes #660.

Updated doc with description of save to workbench

---

mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/quick_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/quick_options_presenter.py
mslice/tests/quick_options_test.py

Allows the user to change font sizes on slice plots using the quick options (right click). I have no added this functionality to the settings menu as it could crowd the menu, but could do if it is desired.
quick label options now trigger via a qt signal as per quick axis options. Relevant unit tests have been updated to reflect this.
1) Open MSlice (Interfaces > Direct > MSlice)
2) Use file browser on data loading tab to load appropriate data (MAR21335_Ei60meV used)
3) Click display on slice sub-tab on Workspace Manager tab.
4) Right click on the following features, and change the font size using the spinbox. Following the change on font size, right click on the feature again and check the spinbox contains the correct value.
> - Plot Title
> - Axis Labels
> - Axis Tick Labels
> - Colorbar …

Add ability to change slice plot font sizes using quick options

---

mslice/app/mainwindow.py

During last release, the `add_action` feature of `plot_window` was updated so that visibility is set to 'False' by default. The associated call to this function with regards to default energy units has been updated to set visibility to 'True'.
**To test:**
1) Open MSlice
2) Click Options -> Default Energy Unit
3) Check Menu is populated
Fixes #712

Fix "Menu for Default Energy Unit empty"

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/quick_options.py
mslice/presenters/plot_options_presenter.py
mslice/presenters/quick_options_presenter.py
mslice/tests/plot_options_presenter_test.py
mslice/tests/quick_options_test.py

This fixes various issues with the "show legends" checkbox on the plot options window, and related line specific "show legend" checkboxes.
**To test:**
- In the Workspace Manager tab select the workspace MAR21335_Ei60meV
- Navigate to the Cut tab
- In the row labelled along, set the from value to 0 and the to value to 10
- In the row labelled over, set the from value to -5 and the to value to 5
- Click Plot. A new window with a cut plot should open.
Ensure:
-"Legends" toggle button on plot window aligns with "Show Legends" checkbox at the top of the "Legend and Line Options page. Check that toggling button off/on effects the checkbox, and vice versa.
- When show legends is unchecked, any line specific "show legend" checkboxes are disabled. When checked, the line …

Fix "Legends enabled in plot options and quick option despite being disabled on plot window"

---

mslice/plotting/plot_window/cut_plot.py

PR#710 extended the quick option interface to allow for the changing of font size. The slice plot model was updated to provided the properties necessary to enable this feature, but the cut plot model was not. 
This PR updates the cut plot model to enable this.
**To test:**
-In the Workspace Manager tab select the workspace MAR21335_Ei60meV
-Navigate to the Cut tab
-In the row labelled along, set the from value to 0 and the to value to 10
-In the row labelled over, set the from value to -5 and the to value to 5
-Click Plot. A new window with a cut plot should open.
-Right click on axis label to open quick options
-Check that changing the font size works as per slice plots.
Fixes #715.

Update cut plot to allow for new font size quick options

---

mslice/cli/plotfunctions.py
mslice/plotting/plot_window/cut_plot.py
mslice/views/slice_plotter.py

Added fixes for matplotlib functionality that is deprecated since 3.2.1 so that MSlice can be used with matplotlib 3.5 but still works with older versions as well (3.2.1 on Windows and 2.2.3 on Linux). 
**To test:**
1. Open MSlice
2. Load data, for instance MAR21335_Ei60meV.nxs from unit tests
3. Click Display on Slice tab and check that there are no error messages
4. Navigate to Cut tab
5. Enter '0' in the 'from' boxes as well as '1' in the 'to' boxes for x and y
6. Enter '0.2' in width
7. Click Plot and check that there is no error message and no warning apart from 'converting a masked element to nan.'
8. Click Waterfall and try different values for x and y offsets. There should be no warnings or error messages.
Fixes #720.

Update to matplotlib 3.5

---

.github/workflows/deploy_conda_nightly.yml

The github workflow for the nightly build of MSlice did have an empty GIT_DESCRIBE_TAG and therefore the created conda package with a version number of 0.0.0. Now the main branch gets checked out explicitly as this should provide the correct GIT_DESCRIBE_TAG.
**To test:**
Unfortunately this can only be tested by merging the fix into main and checking the nightly conda package one day later. The worst case would be a still incorrect version number.

Explicitly check out main branch

---

.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nighly.yml

For unit tests the aim is to test MSlice with the nightly versions of the Mantid conda packages and not with the released Mantid conda packages so that any problems caused by recent changes in these packages can be detected.
It is not necessary to install mantid and mantidqt with the mantid/label/nightly label as this is set in the environment file. However, once there are both main and nightly versions available for mantid and mantidqt this modification ensures that the nightly version and not the main version is used.
**To Test**
Check that unit tests were successful.

Use conda packages with mantid nightly label for unit tests

---

mslice/models/slice/slice_functions.py

Before issue 739 was fixed this caused an error message for slice plots with arbitrary nuclei on step size changes. After fixing 739 there would be no error message anymore but it is still worthwhile to replace the default argument of the function with a check within the function.
**To test:**
Code review only.
Fixes #732

Replace default argument with check within function

---

mslice/presenters/cut_widget_presenter.py

Replaced the error message displayed when attempting to plot a cut without specifying cut axes.
**To test:**
Open a data set in MSlice and navigate to the Cut tab. Without entering any values, click on Plot and check the error message displayed on the bottom of the MSlice window.
Fixes #734

Replaced error message for empty cut axes

---

mslice/plotting/plot_window/slice_plot.py

Fixed colorbar crash when changing scale to logarithmic with negative vmax value and/or negative/0 vmin value.
What was happening was if the min was 0 and the max negative, the values would be switched. The negative value of vmin would then be set to equal to 0.001, making it higher than the max. This causes an exception in matplotlib. Equally if both values were negative, the min would be set to equal 0.001, then not switched with the negative max as switching occurs first. 
**To test:**
-Load MAR21335_Ei60meV dataset
-In the Workspace Manager tab select the workspace MAR21335_Ei60meV
-Navigate to the slice tab, click Display
-Right click on colorbar axis
-Ensure the logarithmic box is checked
-Ensure min is set to 0.0
-Set Max to any negative value.
-Click Ok, …

fix colorbar crash #REF731

---

mslice/plotting/plot_window/interactive_cut.py

In previous versions of matplotlib, the `set_active(False)` function causes the drawn rectangle to not be included on the axis (Its not immediately obvious my why this happens). In more recent versions of matplotlib, this is not the case, so I've set the visibility to false directly.
**To test:**
1. Open a data set in the MSlice interface of Mantid.
2. Display a slice plot.
3. Click on 'Interactive Cuts'
4. Select region by selecting a rectangular region on the slice plot.
5. Close the newly opened cut window.
6. Observe the selected region removal.
Fixes #730.

Fix "Rectangle for interactive cuts remains visible when closing cut window or disabling interactive cut"

---

mslice/plotting/plot_window/interactive_cut.py

In previous versions of matplotlib, the `set_active(False)` function causes the drawn rectangle to not be included on the axis (Its not immediately obvious my why this happens). In more recent versions of matplotlib, this is not the case, so I've set the visibility to false directly.
**To test:**
1. Open a data set in the MSlice interface of Mantid.
2. Display a slice plot.
3. Click on 'Interactive Cuts'
4. Select region by selecting a rectangular region on the slice plot.
5. Close the newly opened cut window.
6. Observe the selected region removal.
Fixes #730.

Fix rectangle visibility bug #REF730

---

mslice/presenters/cut_plotter_presenter.py

The lines for Bragg peaks were to small on interactive cuts due to a hardcoded scale factor. This scale factor was increased to a more suitable size.
**To test:**
Add a Bragg peak to an interactive cut and a normal cut plot. They should have similar sizes.
Fixes #735

Changed default size for Bragg peaks on interactive plots

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/overplot_interface.py
mslice/views/cut_plotter.py

For interactive cuts the enabled Bragg peaks now remain checked when flipping the axes and are redrawn on the new plot.
**To test:**
Add a Bragg peak to an interactive cut and flip the axes a couple of times. The Bragg peak should remain enabled and the corresponding lines be adapted to the current plot.
Fixes #740

Redraw Bragg peaks when axes flipped in interactive cut

---

mslice/plotting/plot_window/cut_plot.py
mslice/scripting/helperfunctions.py
mslice/tests/cut_plot_test.py
mslice/tests/scripting_helperfunctions_test.py

#REF731
This fixes the crash that occurs when setting axes to log scale.
This was caused my a deprecation of the `linthreshx/y` kwarg in matplotlib 3.3.
Note that issue #731 refers to two other bugs when using the plot options and when setting the color bar to log scale with a negative min value:
- For the bug when using plot options, I cannot replicate this exactly. I get the same error message as when changing via the    
quick options (which this PR fixes). I have tried to replicate this using the mantid nightly build, a local mslice build using an 
older version of matplotlib, and a conda build of mslice using an updated version of matplotlib
- The colorscale bug occurs only when setting the max value as a negative when using a log scale. This is a seperate issue, …

Fix Crash when setting axes to log scale

---

mslice/models/colors.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/colors_test.py
mslice/tests/quick_options_test.py

Instead of using the colour name directly in set_option now the name_to_color function from mslice.models.colors is used. This ensures that a colour name is always mapped to the same hex value. The hex mapping for basic colours has been updated as well to reflect the colour scheme changes within matplotlib. The hex values are now hardcoded instead of generated dynamically on start up to speed up plotting. It is still possible to use colours that are not included in the basic colour mapping though.
**To test:**
Create a cut plot with several lines and change a line setting, for instance 'Show Legends'. After clicking on Ok the colours of the lines should not change.
Also, try to re-test https://github.com/mantidproject/mslice/issues/550 as this should still be fixed.
Fixes #733

Colour scheme is now consistent within MSlice

---

mslice/workspace/helperfunctions.py
mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py
mslice/workspace/workspace_mixin.py

This PR ensures the hidden raw and histogram workspace gets renamed when the associated data is renamed in the workspace
manager. Without this, the raw data associated with a renamed dataset is overridden and invalidated if the original file is loaded back into MSlice.
**To test:**
- Load dataset
- Rename dataset using workspace manager tab
- Load same dataset again
- Click to switch between workspaces on the workspace selector
It would also be good to do this test for MatrixWorkspaces, HistogramWorkspaces, and Pixel Workspaces to make sure each case is working.
Fixes #753

Fix crash when reloading the same data after a rename

---

mslice/plotting/plot_window/cut_plot.py

If not an interactive cut, the `set_is_icut` function of `cut_plot` connected the `button_pressed` and `picking` events for a second time (they are initially connected in `__init__` in `PlotFigureManagerQT`).
This PR ensures this does not happen.
**To test:**
1) Plot a cut
2) double click on axis/label/line
3) ensure options only opens once as expected.
Fixes #675.

Fix double opening dialog

---

mslice/plotting/plot_window/slice_plot.py
mslice/tests/slice_plot_test.py

This PR fixes an issue causing very slow plotting times for large datasets. These slow plotting times could be seen whenever making a change to a plot (such as zooming in or out on a plot with recoil lines or bragg peaks), whenever 'Show legend' was turned on. The slow plotting was caused by the computationally expensive process used in matplotlib to find the 'best' legend location, as described in https://github.com/matplotlib/matplotlib/issues/12120/ .
I decided the best solution was to set the location of the legend to be 'upper right' by default, and then the legend can be easily moved by dragging if required by the user. I think in most cases, the upper right location would be a fairly sensible location.
This PR also fixes a problem where the legend would …

Speed up plotting when using a Slice plot legend

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/slice_plot.py
mslice/tests/quick_options_test.py

Default line width is 1.5, previously only integers line widths could be specified through plot options. This PR introduces line widths at 0,5 intervals.
**To test:**
1) Plot a cut plot
2) Open plot options
3) Observe default line width 1.5
4) Click Ok, observe no change to line width
5) Through plot options, test other line widths
Fixes #757.

Fix Default line width not configured correctly

---

mslice/presenters/quick_options_presenter.py
mslice/tests/quick_options_test.py

This PR fixes an issue where the vmin would not be updated if you changed it along with the Logarithmic option (turning it off)  at the same time in the colorbar options menu.
**To test:**
1. Load data into Mslice
2. Go to the Slice tab and click Display
3. Double click the colorbar to open the options
4. Tick Logarithmic and click Ok
5. Double click the colorbar again to open the options. The vmin should be 0.001.
6. Change the vmin to 0, and untick Logarithmic. Click Ok
7. Open the colorbar options again. Vmin should say `0` and not `0.001`
No related issue

Fix vmin not updated when unticking logarithmic

---

mslice/plotting/plot_window/cut_plot.py

In previous versions of mslice, the offset feature of waterfall graphs was applied to error bars using the `set_offsets` function of `LineCollection`, with the `_offset_position` property set to `data`. 
In matplotlib >3.3, the ability to change the `_offset_position` was deprecated. A subsequent change to MSlice removed code that previously did this.
In this state, the `set_offsets` function sets by _pixel_ rather than by datapoints meaning that offsets were applied incorrectly. The ability to set by data has effectively been removed. Converting between data and pixels is not a viable solution due to zoom functionality.
In this fix we access the protected member function of `LineCollection`, `_paths` to manually apply the offsets.
**To test:**
NOTE: These tests must …

Fix error bar offset bug #REF738

---

mslice/plotting/plot_window/cut_plot.py

After merging a bug fix two imports were missing and caused the unit tests to fail. I've just added both back as they are still required:
from distutils.version import LooseVersion
from matplotlib import __version__ as mpl_version

Resolving conflict with missing imports

---

mslice/plotting/plot_window/cut_plot.py

Previously, if the axis of a cut plot with bragg peaks was changed to logarithmic the `get_min` function throws a value error.
This is because the bragg preak data has a differing number of elements to the spectra data - something the `np.greater` function used can't handle.
The function now performs the operation row by row to alleviate this issue.
**Note:** As part of this PR I've removed the suppression of warnings in the `get_min` function, as I can't see any reason for it.
**Note 2:** This PR does not change the way the coordinates of Bragg peaks are specified. As such, when the y axis is set to log the peaks look like this:
I suspect we would rather they look like this?
If so I will create a subsequent PR/Issue.
**To test:**
1) Load any data
2) Plot a cut
3) Add …

Fix ValueError caused by function get_min

---

mslice/app/mainwindow.py

Previously  the warning upon start-up  regarding the change of default cut to cut by integration was formatted to look nice in the console in pycharm. When printed to the mantid console, it does not look right at all.
I've updated the formatting to correct this.
**To test:**
Open mslice via mantid, observe formatting of output warning looks ok.

Change formatting of start up warning re change to cut by integration

---

mslice/plotting/plot_window/plot_options.py
mslice/plotting/plot_window/quick_options.py

This PR uses a custom Line Edit Double Validator to ensure only double values are entered into the min and max axes value boxes for the quick options and plot options. This can prevent confusing error messages.
**To test:**
See the test instructions in the issue.
1. Try opening the Plot options using the cog, and try changing the double values to invalid values.
2. Try opening the Axes Quick options and do the same.
Fixes #765

Prevent strings in options for plot min and max axes values

---

mslice/models/workspacemanager/workspace_algorithms.py
mslice/presenters/data_loader_presenter.py
mslice/tests/workspace_algorithms_test.py

~~**Need to wait for https://github.com/mantidproject/mantid/pull/33981 to get merged**~~
This PR fixes an error caused when loading OSIRIS data due to the OSIRIS data file containing spectra which do not correspond to detectors at the end of the file.
I am unsure if this OSIRIS data is valid data to be loaded into the interface, however there was an easy way to prevent the error, which was caused by an dangerous assumption that the number of histograms == number of detectors.
**To test:**
1) Load the following data into mslice
[OSIRIS00144076.zip](https://github.com/mantidproject/mslice/files/8772816/OSIRIS00144076.zip)
2) Click OK on the pop up that appears upon load.
3) Observe that there isn't an error in the log, but I nicer error in the status bar.
4) In the …

Prevent error when loading OSIRIS data

---

mslice/app/mainwindow.py
mslice/app/mainwindow.ui
mslice/cli/_mslice_commands.py
mslice/models/cut/cut.py
mslice/models/cut/cut_functions.py
mslice/scripting/helperfunctions.py
mslice/tests/command_line_test.py
mslice/widgets/cut/cut.py

Reverts the default cut algorithm back to `Rebin` from `Integration`.
After some discussions in the excitations group it was decided that the breaking changes by switching the default algorithm ( #717 ) is too major a change without pre-notification for users. In addition it was pointed out that for cuts which integrated in Q, the `Rebin` behaviour _could_ be more appropriate, whereas for integration in E, the `Integration` behaviour should usually apply. The previous issue #705 which requested the change in default was focused only on the integration in E behaviour.
So, for now the behaviour should be reverted back to the previous default (to use `Rebin`).
**To test:**
* Start MSlice
* Check that the menu option for the Cut Algorithm is set to `Rebin`
* Load a …

Revert default Cut algo to Rebin

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/overplot_interface.py
mslice/plotting/plot_window/slice_plot.py
mslice/presenters/cut_plotter_presenter.py
mslice/presenters/slice_plotter_presenter.py
mslice/tests/cut_plot_test.py
mslice/tests/slice_plot_test.py

Previously, the y-coords of Bragg peak lines (which have no physical significance) would not scale when the y axis is set to logarithmic. This means the lines become stretched, not appearing unobtrusive markers as intended (see image on issue).
Through this PR, the Bragg peak lines are now scaled to take up a proportion of the axis (currently hardcoded as 15%) either side of a provided datum (set as the median value of the spectra). As such, they also are refreshed (removed and replotted) every time a change is made to the y axis.
**To test:**
1. Plot cut plot
2. Add Bragg Peaks
3. Change the y axis to logarithmic
4. Change the y axis to reflect the following scenarios:
- Negative y values
- Negative y minimum
- 0 minimum
- 0 maximum
5. Confirm behaviour of recoil …

Fix scaling of Bragg peaks for log scales

---

mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_window.py

A bug was caused by the waterfall x and y edit boxes never losing focus on a cut plot. Once either box was selected every subsequent action caused by clicking on a menu/plot takes focus away from the box, but then seems to gives it back again as  the clicked object has `qt focus policy` set to disabled by default. This causes an unnecessary signal and subsequent call to `toggle_waterfall` upon each action.
Upon closing a cut plot, the erroneous signal is emitted in this way, but the `toggle_waterfall` function called after the plot has been closed.
This conflicts with a recent change which requires the `toggle_waterfall` function to update the bragg peak lines when called (this may be unnecessary, considering removal in subsequent PR),
This PR ensures that the …

Fix bug that causes continual calls to "toggle_waterfall"

---

mslice/models/colors.py
mslice/plotting/plot_window/cut_plot.py

**To test:**
Line quick options (specifically the functions that deal with Bragg peaks) had not been updated for the new colour mapping or line width changes.
This PR updates them to not expect an int, and adds default Bragg peak colours to the colourmap,
1. Plot a cut
2. Add Copper Bragg peaks
3. Right Click on Bragg peak lines
4. Observe correct colour and line width in boxes
5. Click ok, no error
No Issue

Fix bragg peak qops to work with new colour mapping and line width

---

mslice/plotting/plot_window/slice_plot.py
mslice/presenters/slice_widget_presenter.py

This PR fixes an error when closing an interactive plot after having closed its associated slice plot. The solution was to disassociate the interactive plot from the slice plot when the slice plot gets closed.
It also removes an unwanted traceback import which I believe was used for debugging but is no longer needed.
**To test:**
1. Load data
2. Display a slice plot
3. Do interactive cut on this plot
4. Close slice plot window
5. Close interactive cut window
6. There should be no error!
Fixes #798

Fix error when closing interactive plot

---

mslice/plotting/globalfiguremanager.py
mslice/plotting/plot_window/interactive_cut.py
mslice/plotting/plot_window/plot_figure_manager.py
mslice/plotting/plot_window/slice_plot.py
mslice/views/slice_plotter.py

Previously, if changing intensity with `interactive cut` toggled on and an `icut ` open, a second slice plot would appear and the rectangle selector would disappear. 
Also, when changing intensity prior to the plotting of an `icut`, the rectangle selector and CrossCursor will appear upon interacting with the plot.
This PR resolves these issues.
NOTE: It is a minor annoyance that the rectangle selector flickers upon a change of intensity, not sure how to get rid of this so let me know if you have a solution.
**To test:**
_Second Plot Window_
1.  Plot any slice
2.  Toggle `interactive cut` on the `slice plot` window
3.  Use the rectangle selector to plot an `icut`
4.  Change the intensity type use the intensity drop down menu of the `slice plot` window.
5. Observe …

Fix second slice plot opening when changing intensity with icut open

---

mslice/cli/_mslice_commands.py
mslice/cli/helperfunctions.py
mslice/models/cut/cut.py
mslice/models/intensity_correction_algs.py
mslice/models/slice/slice.py
mslice/plotting/plot_window/cut_plot.py
mslice/plotting/plot_window/plot_window.py
mslice/presenters/cut_plotter_presenter.py
mslice/tests/intensity_correction_algs_test.py
mslice/workspace/workspace_mixin.py

As part of a previous PR, the `GDOS` intensity correction for slices was disabled as it threw an unhandled error on some datasets.
This PR fixes this issue, and enables the ability to apply `GDOS` intensity correction to cuts.
**To test:**
1) Observe all tests pass, including new GDOS tests.
2) Following testing instructions on previous intensity PR (https://github.com/mantidproject/mslice/pull/811), correcting for GDOS instead of suggested intensities
Resolves #817

Fix GDOS intensity correction + enable for cuts

---

mslice/plotting/plot_window/slice_plot.py
mslice/presenters/slice_plotter_presenter.py

**To test:**
1) Load any `.nxs` mslice dataset (I used `MAR21335_Ei60meV.nxs`)
2) `Display` slice
3) Change intensity to `GDOS` via the `intensity` drop down.
4) When promoted to select a temperature, choose `T_Head` from the drop down.
5) Take an interactive cut
6) Observe no crash
Fixes #827

Fix temperature not cached when set from a log/field

---

mslice/workspace/histogram_workspace.py
mslice/workspace/pixel_workspace.py
mslice/workspace/workspace.py

While performing operations like bose or subtract workspaces are renamed internally. This renaming has been slightly modified to prevent the duplication of suffixes like '_subtracted'. 
**To test:**
Follow instructions in https://github.com/mantidproject/mslice/issues/829 and https://github.com/mantidproject/mslice/pull/755.
When generating the script from https://github.com/mantidproject/mslice/issues/829 from scratch the line with 'RenameWorkspace' should not be included anymore. The original script should still run without problems though.
Fixes #829

Prevent duplication of suffix when renaming workspaces

---

.github/workflows/deploy_conda.yml
.github/workflows/deploy_conda_nightly.yml
.github/workflows/online_doc_update.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nighly.yml

Changed all GitHub workflows from Ubuntu-18.04 to Ubuntu-20.04.
**To test:**
Ensure that workflows are still running. For most workflows that will be only possible after merging into main though.
Fixes #837

Updated Ubuntu version to 20.04 in GitHub workflows

---

.github/workflows/unit_tests.yml
mslice/tests/slice_test.py
mslice/tests/workspacemanager_presenter_test.py

We are using the latest version of mock for the unit tests. Mock was upgraded from 5.0.0. to 5.0.1 recently and one of the changes was that calls to `called_once_with` now result in an AttributeError to enforce usage of `assert_called_once_with` instead. 
There are unrelated issues with the mantid and mantidqt nightly at the moment. That is the reason why the unit test workflow uses mantid and mantidqt 6.5.0 at the moment.
**To test:**
Check that the unit tests are running successfully.

Update for latest mock version 

---

mslice/models/colors.py
mslice/tests/colors_test.py

This PR ensures the `color_to_name` and `name_to_color` will return the passed in string if the string is a valid hex code provided by a user. This avoids raising a value error when the color isn't one of the basic types, but is still a color.
**To test:**
Follow the instructions in the issue to test.
Click `Ok` in the plot options to ensure no error when the users custom color is still selected.
Fixes #847

Allow custom hex color when opening plot options

---

mslice/models/cut/cut.py

As GDOS intensity correction does not currently work correctly regarding cuts, a warning has been added when a user uses this feature.
<!-- Instructions for testing. --
1) Load an mslice dataset, plot slice
2) Use interactive cut to plot a cut
3) Change the intensity to GDOS via the slice
4) Observe warning emitted.

Add warning to gdos cut intensity correction

---

.github/workflows/deploy_conda.yml
.github/workflows/deploy_conda_nightly.yml
.github/workflows/online_doc_update.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nighly.yml
mslice/tests/plotselector_view_test.py
setup.py

Since the mantid/mantidqt upgrade to Qt 5.15 both MSlice unit test workflows failed with segmentation faults. After running the nosetests and coverage successfully the clean up
routine in mantidqt.utils.qt.testing tried to access a QApplication instance that was already closed. This was fixed by removing the start_qapplication decorator that is not 
required in MSlice tests as a QApplication instance is created separately for MSlice tests.
In addition, several components of the GitHub workflows have been upgraded:
- Ubuntu from 20.04 to latest
- actions/checkout from v2 to v3
- conda-incubator/setup-miniconda from v2.1.1 to v2.2.0
To remove deprecation warnings setuptools is now pinned to 47.0.0 and setup.py is now opening files with the 'r' flag instead of 'rU'. …

Fix for segmentation fault in unit test workflows

---

mslice/models/cut/cut.py
mslice/models/labels.py

When updating the cut axis for an interactive cut plot along 2Theta the comparison of units failed as `2Theta` was compared with `Degrees`. This can be avoided by using the `is_twotheta` method for both units as they are then seen as equal.
This fixes both issues regarding cut plots along 2Theta.
**To test:**
Follow instructions for both original issues. There should be no exception anymore but an interactive cut plot displayed for #859 and no error message for a cut plot via the cut tab for #860.
Fixes #859 
Fixes #860

Check 'Degrees' and '2Theta' for x dimension

---

mslice/models/intensity_correction_algs.py
mslice/tests/intensity_correction_algs_test.py

Fix PR fixes a bug where a second symmetrised intensity correction performed (which only happens when you have an interactive cut open) would overwrite the underlying slice due to `CloneWorkspace`.
The algorithm has been rewritten to make use of mslice workspace specific binary operations, more inline with the other intensity correction algs.
**To test:**
1.  Follow instructions in issue.
2.  Test with PSD dataset 
Fixes #864

864 fix intensity change crash

---

mslice/__init__.py
mslice/models/labels.py

Since Mantid is released now MSlice release-next needs to be merged into main with the new version number 2.6.0.

Merge release-next into main for release

---

mslice/models/workspacemanager/file_io.py
mslice/models/workspacemanager/workspace_algorithms.py

**To test:**
Follow instructions in https://github.com/mantidproject/mslice/issues/830.
This PR ensures that properties of a workspace are only propagated if they are not `None`.
Fixes #830

Fix IndexError caused by saving a slice as a matlab file

---

.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nightly.yml

In both GitHub workflows running unit tests the step running flake8 has been moved before the step installing Mantid to reduce the waiting time in case of formatting errors as the Mantid installation takes much longer than the flake8 check.

Moved flake8 step before step with Mantid installation

---

src/mslice/plotting/plot_window/slice_plot.py
src/mslice/presenters/slice_plotter_presenter.py
tests/slice_plotter_presenter_test.py

Refactors a large function that was getting hard to work with.
Also, I've removed the caching of sample log fields on the `slice_plotter_presenter`. This used to mean that you only had to select a sample log for temperature once, then it would be used for all other subsequent slices. I accidently bypassed this functionality a while ago when adding intensity change for cuts, taking the view that the temperature should be specified for every new dataset introduced.
If users take issue with this, I can reimplement.
**To test:**

Refactor run temp dependant function

---

tests/__init__.py
tests/rebose_algorithm_test.py

This PR ensures that the Mslice algorithms such as `Rebose` get subscribed to the Mantid `AlgorithmFactory` before the tests are run using nosetest. This prevents the following error occuring when attempting to run a test using nosetest:
```
FAILED (errors=1)
Error
Traceback (most recent call last):
File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\unittest\case.py", line 60, in testPartExecutor
yield
File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\unittest\case.py", line 676, in run
self._callTestMethod(testMethod)
File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\unittest\case.py", line 633, in _callTestMethod
method()
File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\site-p …
```

Subscribe MSlice algorithms to AlgorithmFactory before running tests

---

.github/actions/publish-package/action.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nightly.yml

To speed up the unit test workflows and the deploy action `conda install` was replaced with `mamba install`. Also, with the new packaging is it not necessary anymore to install setuptools in the conda environment for tests.
**To test:**
Check that unit test are running successfully.

Replace conda install with mamba install

---

mslice-developer.yml

Ensures that the pre commit package is installed within the developer environment. This means the only manual setup you have to do to activate pre-commit is to do
```sh
pre-commit install
```
**To test:**
Code review

Install pre commit for a developer environment

---

environment.yml

This PR pins Openssl to `1.1.*` in order to ensure that Mantid can be installed without conflicts. Previously, the "Setup Miniconda" step would install openssl version 3.1.0 . This was not compatible with the install of Mantid which pins openssl to `1.1.*`. I think the large jump in ssl version meant that it could not resolve the conflict automatically.
We should keep note to update our openssl pinning when Mantid updates it.
I also moved pytest up to be in alphabetical order in the dependency list.
**To test:**
Check the unit test job on this PR passes

Pin Openssl to ensure Mantid is installed without conflicts

---

src/mslice/plotting/plot_window/slice_plot.py

This PR ensures that the axis limits for a slice plot get reset to their original values when the selected intensity is changed. The toolbar history gets cleared inside the matplotlib code when a new intensity is plotted, and so we believe this might be the best option for us currently.
**To test:**
Follow the instructions in the attached issue
Fixes #841

Prevent axis restriction after intensity change

---

src/mslice/app/mainwindow.py
src/mslice/app/mainwindow.ui
src/mslice/cli/helperfunctions.py
src/mslice/models/alg_workspace_ops.py
src/mslice/presenters/cut_plotter_presenter.py
src/mslice/presenters/cut_widget_presenter.py
src/mslice/views/interfaces/cut_view.py
src/mslice/widgets/cut/cut.py
tests/cli_helper_functions_test.py
tests/cut_plotter_presenter_test.py

This PR adds a warning when a step for a cut plot is smaller than the steps in the x axis data of a workspace. This can cause plots to appear to having missing lines. It has been implemented as follows:
- From the cli, a warning message will be output to the log
- From the interface, a warning message will be displayed in the status bar
**To test:**
Follow the instructions in the testing issue
Make sure two warnings are output after running the script, and that they make sense. (two warnings because two of the lines have cut axis steps which are too small)
Repeat the same steps but via the interface. See that a warning is displayed in the status bar.
Fixes #842 
Fixes #728

Add warning for small step Cut Plots

---

src/mslice/presenters/cut_plotter_presenter.py
tests/cut_plotter_presenter_test.py

This PR fixes a bug where the Bragg Peak lines displayed on an interactive cut are too large. They default to having 90% the length of the y axis. Instead, we want the bragg peaks to be 10% of the maximum signal - as is done for a direct cut.
Follow the testing instructions in the issue. You should get bragg peaks similar in size to this:
Fixes #853

Fix Bragg peak too large on interactive cuts

---

src/mslice/app/mainwindow.py
src/mslice/models/workspacemanager/file_io.py
src/mslice/models/workspacemanager/workspace_algorithms.py
src/mslice/presenters/workspace_manager_presenter.py
src/mslice/widgets/workspacemanager/command.py
src/mslice/widgets/workspacemanager/workspacemanager.py
src/mslice/workspace/workspace_mixin.py
tests/file_io_test.py
tests/workspace_test.py
tests/workspacemanager_presenter_test.py

This PR fixes an issue where the metadata for a workspace based off the NXSPE file format was not being saved correctly. Previously, we were using the `SaveNexus` file to save the NXSPE workspace, however we should have been using `SaveNXSPE` to ensure all the correct metadata gets saved.
It was decided that we would not add an explicit option to save NXSPE files via the interface. Instead, I added a check to see if the algorithm history says the file was loaded in from a .nxspe file or .nxs file. If it finds the file was loaded using the `LoadNXSPE` algorithm, then the corresponding save algorithm would be used to save it. Otherwise, the `SaveNexus` algorithm gets used.
This ensures the saved nxspe workspace can be loaded back into the MSlice interface without …

Support saving of NXSPE files 

---

src/mslice/models/alg_workspace_ops.py
tests/alg_workspace_ops_test.py

This PR ensures that the number of steps in an axis gets rounded to the closest whole number if `(axis.end - axis.start)/axis.step` is close to a whole number. We might want to adjust the absolute tolerance in the future if 0.05 is too small.
**To test:**
Follow the instructions in the attached issue
Fixes #899

Use closest whole step number if within a small tolerance

---

src/mslice/plotting/plot_window/plot_window.py

This PR ensures we use a `LineEditDoubleValidator` for the waterfall x and y options so that providing a number in broken e notation will not cause a crash. Instead, the value will get reset to the original value.
**To test:**
Create a waterfall plot
Enter '2e' into the x box, and then click on the y box
The x box should switch back to its original value of 0
Try entering valid values and make sure they still work for x and y
Part of  #854

Use LineEditDoubleValidator to prevent broken e notation

---

src/mslice/cli/plotfunctions.py
src/mslice/util/numpy_helper.py
tests/numpy_helper_test.py

This PR fixes an unhandled exception that causes MSlice to crash when the intensity min or max is a nan or inf value. The Intensity min or max should be set to None if this is the case, thereby avoiding a crash.
**To test:**
Follow the instructions in the attached issue.
There should be no crash. The plot generated will be empty and there may be warnings in the console, but this is still an improvement on the previous behaviour.
Fixes #905

Check intensity is a real number

---

README.md

This PR removes a square bracket that is not needed in the README. It can be seen on the README page:
Note that the coverage badge should update after the next successful nightly run.

Remove square bracket in README.md

---

src/mslice/models/workspacemanager/workspace_algorithms.py
src/mslice/workspace/workspace.py

#908 adds a property `is_slice` to workspaces to differentiate between slices and cuts. When you perform a binary operation on an `mslice` workspace, this property was not passed onto the new resultant workspace and therefore lost.
This ultimately caused a crash when setting the intensity of a slice.
**To test:**
1) Plot a slice.
2) Change intensity to `chi`
3) Observe no crash
Fixes #916

Fix crash when changing intensity

---

src/mslice/presenters/cut_plotter_presenter.py
src/mslice/views/cut_plotter.py

#888 Removes a line which changes a `None` `intensity_range` value to `(None, None)`.
This PR effectively readds this functionality, by changing the default value passed as `intensity_range` to `(None, None`) rather than `None`. It does not make sense for the default value to cause a crash when it is not needed for anything else.
**To test:**
Follow steps in #911
Fixes #911

Fix crash when plotting from workspace list

---

src/mslice/cli/helperfunctions.py
src/mslice/models/axis.py
src/mslice/presenters/cut_plotter_presenter.py
tests/axis_test.py
tests/cut_plotter_presenter_test.py

This PR adds a tolerance to axis step validation, preventing a warning bring triggered by precision errors.
I've taken the validation code inside of axis so I only have to define this tolerance in one place. Tests edited/moved to suit.
**To test:**
Run script in #912 
Fixes #912

Add tolerance to axis step validation

---

src/mslice/workspace/histogram_workspace.py

As per a similar bug fix, this PR ensures that `is_slice` propagates on binary operations involving histogram workspaces.
This prevents a crash when correcting the intensity of a slice taken from a pixel workspace to `GDOS`.
This bug was introduced through this pr: https://github.com/mantidproject/mslice/pull/908
**To test:**
1) Load `HYS_63373_4pixel.nxspe`
2) Project, and plot as a slice
3) Take an `icut`.
4) Using the slice window, correct the intensity to `GDOS`.
5) Observe no crash.

Fix crash when correcting GDOS intensity of pixel ws

---

src/mslice/models/intensity_correction_algs.py
tests/intensity_correction_algs_test.py

This corrects a bug where errors were simply being summed as if they were absolute. This is not the case, and they need to be added in quadrature.
https://docs.mantidproject.org/v3.7.2/concepts/ErrorPropagation.html
**To test:**
1). Plot a slice, take a cut where appropriate
2) Correct to GDOS
3) See smaller error bars.

Correct error propagation in GDOS intensity correction

---

src/mslice/models/intensity_correction_algs.py

Currently, when correcting cuts with `GDOS`, the result is stored in the ADS. This PR corrects that.
**To test:**
1) Load `MAR21335_Ei60meV` dataset
2) Take a cut
3) Correct for GDOS
4) In the console run: `from mantid.api import AnalysisDataService as ADS; ADS.getObjectNames()`
5) See no objects stored in ADS.

Stop storing GDOS cuts in ADS

---

.github/actions/publish-package/action.yml
.github/workflows/deploy_conda_nightly.yml

Caused by a known bug in mamba the MSlice nightly builds started to fail recently: https://stackoverflow.com/questions/76847652/mamba-env-throws-attributeerror-namespace-object-has-no-attribute-func)
While we are waiting for a new mamba version with a fix for this I have replaced `mamba build` with `conda build`.
**To test:**
Check that there are no other changes than the one described above and observe that the last run of `Deploy MSlice nightly` with this branch was successful.
It would be useful to check `Deploy MSlice nightly` again the day after this PR was merged into main.

Temporary fix for failing MSlice nightly builds

---

src/mslice/workspace/histogram_workspace.py
src/mslice/workspace/pixel_workspace.py
src/mslice/workspace/workspace.py
tests/histogram_workspace_test.py
tests/pixel_workspace_test.py
tests/workspace_test.py

This PR ensures we escape special characters when renaming workspaces. Previously, renaming a workspace containing a special character would cause an exception.
**To test:**
Load data
Rename the workspace to contain a `)` character
Attempt to rename the workspace a second time
There should be no exception and renaming the workspace should work.
Fixes #934

Escape special characters in workspace name when renaming

---

src/mslice/models/workspacemanager/file_io.py
tests/file_io_test.py

This PR ensures that matlab and ascii files get saved into the default save directory when a relative filepath is provided by the user.
**To test:**
To test this, you will need to make sure your config service returns a default save directory.
Fixes #532

Set default save directory

---

src/mslice/cli/__init__.py
src/mslice/plotting/plot_window/overplot_interface.py
src/mslice/presenters/cut_plotter_presenter.py
src/mslice/presenters/slice_plotter_presenter.py
src/mslice/scripting/helperfunctions.py
tests/scripting_helperfunctions_test.py

This PR ensures the line colors of the bragg and recoil lines on a Cut and Slice plot get propagated to a generated plotting script.
**To test:**
Load data into mslice
Do a slice
Add a bragg peak and recoil line, and change the color
Generate a script to clipboard
Run the script in mantid
The colors should be propagated
Fixes #931

Propagate recoil and bragg line colors to script

---

src/mslice/scripting/__init__.py
tests/scripting_tests.py

This prepends an `r` to the filepath string in generated scripts to ensure `\U` is not interpreted as unicode.
**To test:**
I've struggled to directly test this, as I cannot directly replicate the script that caused the issue. In my case, the generated filepath is separated by `/` not `\`.
Regardless, generated a few scripts of cut/slices from clipboard and test.
Fixes #932

Ensure filepath in generated script is raw string

---

src/mslice/cli/_mslice_commands.py
tests/command_line_test.py

Intensity range should default as a tuple, but this was missed it one place. This PR fixes this.
**To test:**
Run this script: https://developer.mantidproject.org/Testing/DirectInelastic/MSliceTestGuide.html#the-command-line-interface
Fixes #933

Fix out of bounds intensity range issue when plotting from cli

---

src/mslice/models/workspacemanager/workspace_algorithms.py
src/mslice/plotting/plot_window/plot_figure_manager.py
tests/file_io_test.py

This rolls back some changes in #908.
The change of the if conditional to `is_slice` misses the fact that the workspace provided is actually the underlying workspace, which then needs to be converted to a derived workspace before saving.
I've removed the `slice_nonpsd` argument from `save_workspaces` and  `_save_single_ws` as in the only use in the current code it is fed a hardcoded argument as `True` (even though the default was `False`). It was also confusing for two reasons:
-  The workspace being saved could also be a `cut`
- In the `_save_single_ws` function there is the statement `non_psd_slice = slice_nonpsd and isinstance(workspace, Workspace) and not workspace.is_PSD`, which seems to imply inequivalence between `non_psd_slice` and `slice_nonpsd`.
I don't …

Fix save plot saving underlying ws rather than derived ws

---

src/mslice/models/workspacemanager/workspace_algorithms.py
src/mslice/plotting/plot_window/plot_figure_manager.py
src/mslice/plotting/plot_window/slice_plot.py
src/mslice/presenters/slice_plotter_presenter.py
src/mslice/util/intensity_correction.py
tests/plot_figure_test.py

Fixes bug #947 where the saving from the slice plot window saves the underlying workspace rather than the actual plot.
~~This should be considered a temporary fix for Mantid 6.8.~~
~~A full fix for this issue should also include tests (current save functionality is [not tested at all](https://coveralls.io/builds/63125329/source?filename=src%2Fmslice%2Fmodels%2Fworkspacemanager%2Fworkspace_algorithms.py#L239)).~~
~~Also this has been checked on for the "S(q,E)" intensity type and not for others.~~
Edit: PR updated to handle different intensity types and a basic set of tests added.
**To test:**
1. Load any data file
2. Plot a slice ("Display" in the "Slice" tab)
3. Click on the floppy icon on the plot window and save a NeXus `.nxs` file.
4. Load it in Mantid …

Fix slice plot data save bug

---

src/mslice/plotting/plot_window/cut_plot.py
tests/cut_plot_test.py

- Introduced an if statement that checks a boolean flag on whether the legend is supposed to be shown or not.
- Edited the unit test of the changed function to include testing of both options, i.e. when legend is not shown and when legend is shown
- When the legends box is clicked, a `_toggle_legend` function is activated which sets the boolean attribute `_legends_shown` to its opposite
- The attribute `_legends_shown` of `CutPlot` is thus supposed to control whether or not the legend is visible in the plot.
- The `update_legend` function does not make use of the attribute `_legends_shown` in its scope, which leads to legends being shown even when `_legends_shown` is set to False.
- This behaviour is present in 3 scenarios on cut viewer, as all these instances call the function …

Fix legend remaining turned off when Waterfall is clicked

---

src/mslice/plotting/plot_window/cut_plot.py
src/mslice/presenters/plot_options_presenter.py
tests/cut_plot_test.py
tests/plot_options_presenter_test.py

- Fixed bug where data gets distorted from setting log scale to x axis and then setting it to linear again
- Restructured section of the code dealing with updating the log scales on the axes.
**To test:**
- Open cut plot with some example data
- Open plot options > tick Logarithm for x axis > 'OK'
- Check log scale is applied to x axis
- Open plot options again > untick Logarithm for x axis > 'OK'
- Check plot is back to original format
- Repeat the same steps for y axis
- Now put both axis on a linear scale
- Go to Information > Bragg Peaks > check Aluminium
- Change y axis to log scale
- The lines for the Aluminium bragg peaks should stay symmetrical around zero
- Change y axis to linear
- The lines for the Aluminium bragg peaks should stay symmetrical around …

956 data in cut plot distorted after ticking and unticking log scale in x axis

---

src/mslice/app/mainwindow.py
src/mslice/widgets/ipythonconsole/ipython_widget.py

In the past, commands run in the Jupyter console were still visible after closing and re-opening the MSlice interface in Mantid. Now the Jupyter console is cleaned up and opens with `import mslice.cli as mc` just as on the first startup of the interface.
This fixes one part of the bugs described in https://github.com/mantidproject/mslice/issues/737. The second part will be dealt with in changes for https://github.com/mantidproject/mslice/issues/839 and https://github.com/mantidproject/mslice/issues/924.
**To test:**
Copy the `mslice` directory within `src` into `scripts\ExternalInterfaces` for a Mantid 6.8 installation. Open the MSlice interface in this Mantid workbench and use the Jupyter console, for instance by running the following script:
`ws = …

Clean up Jupyter QtConsole when closing MSlice interface in Mantid

---

tests/cut_algorithm_test.py
tests/cut_functions_test.py
tests/cut_normalisation_test.py
tests/projection_calculator_test.py
tests/rebose_algorithm_test.py
tests/slice_algorithm_test.py
tests/slice_functions_test.py
tests/workspace_algorithms_test.py

ADS.clear() now returns a warning. This causes an exception in `tearDown` and `tearDownClass` methods in tests. I have added code to ignore the warning instead.
**To test:**
Check if the unit tests for this branch are passing.

Suppress returned warning from ADS.clear()

---

src/mslice/cli/_mslice_commands.py

The import for Mantid algorithm wrappers was removed by accident earlier this year. It has now been added back.
**To test:**
Follow instructions in original issue.
Fixes #961.

Added import for Mantid algorithm wrappers back into CLI

---

src/mslice/plotting/plot_window/overplot_interface.py

Fixed error by deleting line object directly.
There is no need to call an ArtistList when can just delete the artist directly.
Fixed a bug where removing Bragg peak lines caused an unhanded error. This happened due to matplotib having been updated, and the object ArtistList no longer supporting a remove() method.
**To test:**
Open a slice plot > Information > Bragg peaks > select some bragg peaks
Then try to deselect any bragg peak
The Bragg peak lines should be removed from the plot.
Fixes #967 .

Fixed matplotlib error by avoiding call to ArtistList

---

tests/cut_algorithm_test.py
tests/cut_functions_test.py
tests/cut_normalisation_test.py
tests/projection_calculator_test.py
tests/rebose_algorithm_test.py
tests/slice_algorithm_test.py
tests/slice_functions_test.py
tests/workspace_algorithms_test.py

ADS.clear() now has a silent flag to suppress the warning message (https://github.com/mantidproject/mantid/issues/36690) thrown when running this function. It is useful to set this flag when clearing the ADS after unit tests, as it simplifies the clean-up process.
**To test:**
Check that the unit tests were running without problems for this branch: https://github.com/mantidproject/mslice/actions/runs/7757957015

Update tests with True flag for ADS.clear()

---

src/mslice/models/intensity_correction_algs.py

When creating an MDHisto workspace for a different intensity correction algorithm, this workspace needs to be saved in the ADS. We have tried to prevent this in the past (https://github.com/mantidproject/mslice/pull/925), but it causes crashes when the user wants to access the cut workspace in Mantid Workbench.
Reducing the ADS usage by MSlice is an ongoing maintenance project and there will hopefully be a more sophisticated solution available for the next release.
**To test:**
Follow the steps in the original issue and check that Mantid does not crash anymore.
Fixes #972.

Fix for crash when saving MDHisto into mantid workbench

---

pyproject.toml
tests/intensity_correction_algs_test.py

Recently a unit test failed, caused by a deprecation warning. This problem is described in https://github.com/mantidproject/mslice/issues/975 and will be fixed soon. Since testing for the upcoming MSlice release has already finished, the fix needs to be added after the release. Therefore, this deprecation warning is temporarily suppressed in the project configuration.
**To test:**
Check if the corresponding workflow was running successfully: https://github.com/mantidproject/mslice/actions/runs/8046107930

Fix for deprecation warning

---

.github/actions/publish-package/action.yml
.github/workflows/deploy_conda_nightly.yml

When adding channels for Conda, the last added channel moves to the top. Therefore, it makes more sense to add channel `mantid/label/nightly` before channel `mantid` so that released Conda packages for `mantid` and `mantidqt` are preferred over the nightly versions.
**To test:**
Code review only.

Modify sequence of channels in GitHub publish

---

pyproject.toml
src/mslice/models/intensity_correction_algs.py
tests/intensity_correction_algs_test.py

This is a permanent fix for a deprecation warning that occurred in the unit tests. Conversion of an array to a scalar is deprecated in NumPy 1.25. In the function sample_temperature in the intensity correction algorithms, we attempted to convert a one-dimensional array into a float. This triggers now the deprecation warning. The solution is to first check for lists and arrays before attempting to convert a single value to a float.
**To test:**
1. Load `MAR21335_Ei60meV` dataset 
2. Display slice
3. On the intensity dropdown select `Chi''(Q,E)`
4. Enter `80` in combo box and click ok
5. On the intensity dropdown select `GDOS`
6. There should be no pop up window asking for the sample temperature
Also, check that the unit tests were running without failure for this …

Permanent fix for deprecation warning

---

.github/workflows/deploy_conda.yml
.github/workflows/deploy_conda_nightly.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nightly.yml

All unit test workflows fell over for MSlice, although there were no changes made to the MSlice main branch (which is used for the nightly unit test workflow). Switching from `mamba install` to `conda install` can prevent this. 
I have also upgraded the conda-incubator from version 2.2.0 to version 3.
**To test:**
Check that the GitHub workflow for the unit tests does not fail for this branch: https://github.com/mantidproject/mslice/actions/runs/8433683620

Fix for failing unit test workflows

---

src/mslice/plotting/plot_window/plot_figure_manager.py

When trying to save an `.nxs` file as `.nxspe`  or vice versa from a slice plot, MSlice crashed, as this is not supported. Now a box with an error message opens instead.
**To test:**
Follow the instructions on the original issue. In addition, attempt to save an `.nxspe` file as `.nxs`.
Fixes #984.

Fix for crash when saving into incorrect format

---

src/mslice/models/intensity_correction_algs.py
src/mslice/workspace/histogram_workspace.py
tests/histogram_workspace_test.py

When the intensity of a cut is changed to GDOS, a two-dimensional MDHisto workspace is created. When converting this to a matrix workspace, the bin size needs to be calculated on base of the second dimension, not the first. I have also added an error message in case a one-dimensional workspace or the second dimension does not have the correct size. This check is now also covered by a unit test.
**To test:**
Follow the instructions in the original issue: https://github.com/mantidproject/mslice/issues/986
In addition, please also check that the following problem does not re-occur: https://github.com/mantidproject/mslice/issues/972
Fixes #986.

Fix for empty mdhisto lines

---

src/mslice/plotting/plot_window/plot_options.py

Added a new line style, "None". Here, only the error bars are plotted and not the line. 
**To test:**
1. Load a workspace into MSlice
2. Do a cut
3. Click on the settings icon and change the line style to 'None'
4. Observe that the cut only shows error bars and no line
5. Change the line style to any of the other options
6. Check that the line on the plot is shown with the corresponding line style
Fixes #981

Added None as a line option

---

src/mslice/models/workspacemanager/file_io.py

The spectrum ID is now omitted when saving a 2D workspace as an ASCII file.
**To test:**
1. Load a workspace into MSlice
2. Select the workpace in the 2D tab of the workspace manager
3. Click the Save button and select ASCII
4. Check that the second line remains empty
Fixes #993.

Omit spectrum ID when saving as ASCII

---

.github/actions/publish-package/action.yml
.github/workflows/deploy_conda.yml
.github/workflows/deploy_conda_nightly.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_nightly.yml

The option to set mambaforge as a miniforge-variant for the conda incubator is deprecated as mambaforge and miniforge are identical within the conda incubator:
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
Subsequently, this setting has been removed in all our GitHub workflows.
**To test:**
Check that the GitHub workflow after pushing to the branch of this PR does not fail: https://github.com/mantidproject/mslice/actions/runs/10937162011

Remove mambaforge as miniforge-variant in workflows

---

docs/source/quickstart.rst

The MSlice documentation provides information for the user on how to replace MSlice within Mantid Workbench. From Mantid 6.12 on, MSlice will not be an external interface anymore, but a conda package. This needs to be reflected in these instructions.
**To test:**
Please read the instructions and verify whether they make sense. Also, check spelling and grammar.

Updated mslice docs after interface updates in Mantid

---

src/mslice/util/numpy_helper.py

We had reports of random Mantid crashes with the following stack trace:
`Stack Trace:
Traceback (most recent call last):
File "/opt/mantidworkbench6.11/scripts/ExternalInterfaces/mslice/util/numpy_helper.py", line 14, in apply_with_corrected_shape
return_value = method(shape_array, array)
ValueError: operands could not be broadcast together with shapes (123,) (124,)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/mantidworkbench6.11/scripts/ExternalInterfaces/mslice/plotting/plot_window/cut_plot.py", line 563, in show_intensity_plot
if not self._run_temp_dependent(method, previous_type):
File "/opt/mantidworkbench6.11/scripts/ExternalInterfaces/mslice/plotting/plot_window/cut_plot.py", line 576, in …

Catch error for vectors of different length

---

conda/meta.yaml
pyproject.toml
src/mslice/cli/_mslice_commands.py
src/mslice/models/colors.py
src/mslice/models/intensity_correction_algs.py
src/mslice/models/workspacemanager/workspace_algorithms.py
src/mslice/models/workspacemanager/workspace_provider.py
src/mslice/plotting/plot_window/iplot.py
src/mslice/plotting/plot_window/plot_figure_manager.py
src/mslice/plotting/plot_window/plot_options.py
src/mslice/presenters/interfaces/data_loader_presenter.py
src/mslice/presenters/interfaces/main_presenter.py
src/mslice/presenters/interfaces/plot_selector.py
src/mslice/presenters/interfaces/powder_projection_presenter.py
src/mslice/presenters/interfaces/slice_plotter_presenter.py
src/mslice/presenters/interfaces/workspace_manager_presenter.py
src/mslice/presenters/quick_options_presenter.py
src/mslice/presenters/workspace_manager_presenter.py
src/mslice/scripting/__init__.py
src/mslice/util/mantid/algorithm_wrapper.py
src/mslice/util/mantid/mantid_algorithms.py
src/mslice/workspace/base.py
tests/cut_widget_presenter_test.py
tests/energy_units_test.py

To ensure compatibility with both Python 2 and 3, MSlice used the `six` library. This PR moves it on to Python 3 code instead.
**To test:**
Code review and observe that tests pass.
Fixes #1039.

Replaced six with Python 3 code

---

src/mslice/models/mslice_ads_observer.py
src/mslice/models/workspacemanager/workspace_provider.py
src/mslice/plotting/plot_window/interactive_cut.py
src/mslice/plotting/plot_window/slice_plot.py
src/mslice/presenters/workspace_manager_presenter.py
src/mslice/widgets/workspacemanager/workspacemanager.py
tests/workspacemanager_presenter_ads_test.py
tests/workspacemanager_presenter_test.py

So far MSlice interacted with the ADS in a one-sided way. Some of its workspaces were stored in the ADS and occasionally deleted, but changes to the ADS from the Mantid side ignored. This sometimes led to missing workspaces in MSlice when the respective workspace was deleted on the Mantid side. However, the respective workspace would still get displayed in MSlice and cause a crash when selected.
This PR introduces an ADS observer that modifies MSlice workspaces on delete, clear and rename, respectively. 
In addition, two small bugs were fixed that became obvious when testing these changes:
1. When taking an interactive cut and closing the interactive cut window without saving the cut to the workspace, a cut was showing up in the MD Histo tab. 
2. When clearing all …

Added ADSObserver to MSlice

---

src/mslice/models/workspacemanager/workspace_provider.py
src/mslice/util/mantid/algorithm_wrapper.py

Deleting a workspace within MSlice that is also in the ADS caused a crash in Mantid. The reason was that deleting the workspace in MSlice updated the ADS and, as a result, the ADS triggered a deletion request for this workspace in MSlice. This request then failed as the workspace was already deleted within MSlice. To avoid this situation, MSlice does not attempt to delete non-existing workspaces anymore. In addition, all corresponding hidden workspaces are now deleted from the ADS as well.
**To test:**
Follow the instructions on the original issue.
Fixes #1044.

Improve deletion of workspaces that are in the ADS

---

src/mslice/models/workspacemanager/workspace_provider.py

When testing the new ADS observer, unreliable unhandled exceptions occurred when following testing instructions in https://developer.mantidproject.org/Testing/Direct/MSliceTestGuide.html#interaction-with-ads. This PR catches these exceptions to avoid crashes.
**To test:**
Replace the MSlice version in the current Mantid nightly and follow the instructions in the issue below.
Fixes #[38675](https://github.com/mantidproject/mantid/issues/38675)
(Since this is in a different repo, we will have to manually close this Mantid issue.)

Catch unhandled exceptions

---

src/mslice/presenters/workspace_manager_presenter.py

Added code that allows the user to delete a hidden workspace in the ADS, so that the corresponding workspace is deleted in MSlice as well. This prevents crashes when this workspace is accessed again after deletion. Before, this was only possible with visible workspaces.
**To test:**
Follow the steps to reproduce this problem in the original issue.
Fixes #1050.

Remove invisible workspace from MSlice when deleted in ADS

---

src/mslice/app/mainwindow.py
src/mslice/app/mainwindow.ui

The `Compose` button now has a similar layout as the `Save` button. This should make it easier to select a compose action on some operating systems, for instance, macOS, where the selection was sometimes difficult due to a squashed layout.
**To test:**
Follow the instructions in this Mantid issue: https://github.com/mantidproject/mantid/issues/38671

Changed layout of Compose button

---

src/mslice/models/cut/cut.py
src/mslice/widgets/cut/cut.py

Due to rounding errors MSlice sometimes assumed a set width for producing more than one cut when only one cut was intended. This has been fixed by setting the width to None if no value was provided.
**To test:**
Please replace MSlice in an installed Mantid with the version from this branch and follow steps in the original issue.
Fixes #[39285](https://github.com/mantidproject/mantid/issues/39285) - Might need to get closed manually as it is a Mantid issue.

Fix for bug in width calculation

---

src/mslice/presenters/cut_widget_presenter.py
src/mslice/widgets/workspacemanager/input_boxes.py

During manual testing, a few crashes were caused by entering invalid characters into the boxes for `Bose` and `Scale` for `Compose` as well as for `Intensity` on the `Cut` tab.
**To test:**
Enter a special character into the boxes mentioned above and observe no crash, but a message warning about the invalid input. In case for the the` Intensity`, the message differentiates between invalid entries for the start and end value.
Fixes #1087

Prevent crash for invalid characters

---

docs/source/quickstart.rst

`MSlice` is turned into an optional dependency of `mantidworkbench`. However, MSlice would still be installed explicitly in IDAaaS and inside standalone packages. The quickstart guide of `MSlice` is to be updated to reflect those changes.
**To test:**
Check that the updated quickstart guide reads well.
Fixes #39237.

Updated MSlice quickstart guide to reflect it as an optional dependancy of conda installs

---

src/mslice/models/alg_workspace_ops.py
src/mslice/presenters/cut_plotter_presenter.py
src/mslice/scripting/helperfunctions.py
tests/scripting_helperfunctions_test.py

Prevent addition of `None` values for width when calculating the cut end. For the issue the crash happened when creating a script from a cut plot. However, the same problem could also occur in the cut plot presenter, so I've applied the same fix there as well.
**To test:**
Please follow the instructions in the original issue. In addition, try to use float values in the `width` box.
Fixes #1105

Fix for save script error

---

src/mslice/plotting/plot_window/cachable_input_dialog.py
src/mslice/plotting/plot_window/cut_plot.py
src/mslice/plotting/plot_window/plot_window.py
src/mslice/plotting/plot_window/slice_plot.py
src/mslice/presenters/slice_plotter_presenter.py
tests/slice_plot_test.py
tests/slice_plotter_presenter_test.py

Adds a temperature log cache to the slice presenter such that subsequent slices will, by default, use that log for setting the temperature of the slice. 
A menu item to allow this option to be set manually has also been added and is available when an appropriate Intensity is selected.
**To test:**
1. Load `MAR21335_Ei60meV` from the ISIS Sample Data
2. Swap to Workspace Manager and click `Display`
3. Change the Intensity in the menu bar to `Chi''(Q,E)`
4. Check that the `Set Temperature Log` option starts greyed out.
5. Select `moderator_temp` and tick `Overwrite Cached Value`.
6. Close the plot.
7. Click `Display` again. 
8. Select `Intensity` -> `Chi''(Q,E)` again.
9. No dialog should appear, as it is now automatically using the previously selected log.
10. …

Cache the Temperature Log Entered for Use in Subsequent Slices
